/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.                           
 * All rights reserved.                                                        
 *                                                                             
 * Unauthorized use, practice, perform, copy, distribution, reproduction,      
 * or disclosure of this information in whole or in part is prohibited.        
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: 
 * $Date: 
 * $Author: 
 * $CCRevision: pwd_dlg_mlm.c,v $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:                                                                
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                   include files                                               
-----------------------------------------------------------------------------*/
#include "u_common.h"
#include "u_sys_name.h"
#include "c_cl.h"
#include "c_os.h"
#include "amb/a_amb.h"

#ifdef APP_MLMGEN_CUSTOM_LOGIC
#include "res/app_util/mlmgen/a_mlmgen.h"
#endif

/*-----------------------------------------------------------------------------
                    data declarations                                          
-----------------------------------------------------------------------------*/
typedef struct _MLM_PWD_DLG_TEXT_T
{
    UTF16_T     w2s_msg_usrname[10];
    UTF16_T     w2s_msg_pwd[9];
    UTF16_T     w2s_msg_help_enter[8];
    UTF16_T     w2s_msg_help_arrow[4];
} MLM_PWD_DLG_TEXT_T;

static UINT16 ui1_g_mlm_cur_lang_idx = 0xFFFF;
static MLM_PWD_DLG_TEXT_T t_g_mlm_text;

static UINT8   at_g_compressed_eng[] =
{
    0x0b, 0x65, 0x28, 0x66, 0x48, 0x65, 0x28, 0x62, 0x50, 0x60,
    0xc8, 0x63, 0x48, 0x64, 0xc8, 0x05, 0xb2, 0x19, 0x18, 0x02,
    0x80, 0xac, 0x62, 0x20, 0x2c, 0x67, 0xc8, 0x07, 0xca, 0xa4,
    0x00, 0x45, 0x9c, 0x81, 0xac, 0x3c, 0x86, 0x34, 0x86, 0x4c,
    0x20, 0x3f, 0x17, 0xc8, 0x0f, 0x63, 0xc8, 0x66, 0x48, 0x02,
    0xd2, 0x00, 0x00
};

static UTF16_T*    aw2s_g_txt_tbl[4] =
{
    t_g_mlm_text.w2s_msg_usrname,
    t_g_mlm_text.w2s_msg_pwd,
    t_g_mlm_text.w2s_msg_help_enter,
    t_g_mlm_text.w2s_msg_help_arrow
};

static UINT8* apui1_g_data_tbl[1] =
{
    at_g_compressed_eng
};

static SIZE_T az_g_data_len_tbl[1] =
{
    sizeof(at_g_compressed_eng)
};

static HANDLE_T h_g_lock = NULL_HANDLE;

/*-----------------------------------------------------------------------------
                    function declarations                                          
-----------------------------------------------------------------------------*/
static VOID _mlm_pwd_dlg_decompress(UINT16 ui2_lang)
{
    INT32       i4_ret;
    HANDLE_T    h_zip_eng = NULL_HANDLE;
    SIZE_T      z_dest_len = sizeof(MLM_PWD_DLG_TEXT_T);

    if(ui2_lang >= 1)    /* MLM_PWD_DLG_LANG_NUM = 1 */
    {
        return;
    }

    do
    {
        i4_ret = c_cl_open_eng(SN_CL_ZIP, NULL, NULL, &h_zip_eng);
        if(i4_ret < 0)
        {
            break;
        }

        i4_ret = c_cl_decompress(h_zip_eng,
                                 apui1_g_data_tbl[ui2_lang],
                                 az_g_data_len_tbl[ui2_lang],
                                 0,
                                 CL_NULL_PARAM_TYPE,
                                 NULL,
                                 &t_g_mlm_text,
                                 &z_dest_len,
                                 NULL);
        if(i4_ret < 0)
        {
            break;
        }

    }while(0);

    if(i4_ret < 0)
    {
        c_memset(&t_g_mlm_text, 0, sizeof(MLM_PWD_DLG_TEXT_T));
    }

    if(h_zip_eng != (HANDLE_T)NULL)
    {
        c_cl_close(h_zip_eng);
    }
}

static VOID _mlm_pwd_dlg_lock(VOID)
{

    /* Acquire lock */
    if(h_g_lock == NULL_HANDLE)
    {
        a_amb_lock();
        if(h_g_lock == NULL_HANDLE)
        {
            c_sema_create(&h_g_lock,
                          X_SEMA_TYPE_MUTEX,
                          X_SEMA_STATE_UNLOCK);
        }
        a_amb_unlock();
    }

    /* Lock */
    if(h_g_lock)
    {
        c_sema_lock(h_g_lock, X_SEMA_OPTION_WAIT);
    }
}

static VOID _mlm_pwd_dlg_unlock(VOID)
{
    /* Unlock */
    if(h_g_lock)
    {
        c_sema_unlock(h_g_lock);
    }
}

UTF16_T* mlm_pwd_dlg_get_text(UINT16 ui2_lang, UINT16 ui2_key)
{
    if(ui2_lang != ui1_g_mlm_cur_lang_idx)
    {
        _mlm_pwd_dlg_lock();
        if(ui2_lang != ui1_g_mlm_cur_lang_idx)
        {
            _mlm_pwd_dlg_decompress(ui2_lang);
            ui1_g_mlm_cur_lang_idx = ui2_lang;
        }
        _mlm_pwd_dlg_unlock();
    }

#ifdef APP_MLM_CENTER_SUPPORT /* ExcelGen mechanism. */ 
    if (   (aw2s_g_txt_tbl[ui2_key][0] != 0 && aw2s_g_txt_tbl[ui2_key][0] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][1] != 0 && aw2s_g_txt_tbl[ui2_key][1] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][2] != 0 && aw2s_g_txt_tbl[ui2_key][2] == (UTF16_T)L'I')  &&
           (aw2s_g_txt_tbl[ui2_key][3] != 0 && aw2s_g_txt_tbl[ui2_key][3] == (UTF16_T)L'D') )
    {
        extern UTF16_T* mlm_center_get_text_by_hint (CHAR* ps_module_name, UINT16 ui2_lang, UTF16_T* pw2s_hint);

        return mlm_center_get_text_by_hint ("PWD_DLG", ui2_lang, aw2s_g_txt_tbl[ui2_key]);
    }
#endif

    return aw2s_g_txt_tbl[ui2_key];
}

UINT16 mlm_pwd_dlg_s639_to_langidx(ISO_639_LANG_T s639_lang)
{
    UINT16 ui2_lang_idx = 0; 

    if(s639_lang == NULL)
    {
        ui2_lang_idx = 0;
        return ui2_lang_idx;
    }
    if(c_strncmp(s639_lang,"eng",3) ==0)
    {
        ui2_lang_idx = 0; /*MLM_PWD_DLG_LANG_ENG*/
    }
    else
    {
        ui2_lang_idx = 0; /*MLM_PWD_DLG_LANG_ENG*/
    }
#ifdef MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN
    return MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN("PWD_DLG", s639_lang, ui2_lang_idx);
#else
    return ui2_lang_idx;
#endif
}
VOID mlm_pwd_dlg_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang)
{
    if(s639_lang == NULL)
    {
        return;
    }
    switch(ui2_lang)
    {
        case 0: /*MLM_PWD_DLG_LANG_ENG*/
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
        default:
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
    }
}
