/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.
 * All rights reserved.
 * 
 * Unauthorized use, practice, perform, copy, distribution, reproduction,
 * or disclosure of this information in whole or in part is prohibited.
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: #21 $
 * $Date:   
 * $Author: 
 * $CCRevision: $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/
#ifndef _pwd_dlg_mlm_h_
#define _pwd_dlg_mlm_h_

/*-----------------------------------------------------------------------------
                   include files
-----------------------------------------------------------------------------*/
#include "u_common.h"

/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
-----------------------------------------------------------------------------*/
#define MLM_PWD_DLG_TEXT(lang, key) mlm_pwd_dlg_get_text(lang, key)

#define MLM_PWD_DLG_NUM_LANG 1
#define MLM_PWD_DLG_NUM_KEY 4

#define MLM_PWD_DLG_KEY_MSG_USRNAME 0
#define MLM_PWD_DLG_KEY_MSG_PWD 1
#define MLM_PWD_DLG_KEY_MSG_HELP_ENTER 2
#define MLM_PWD_DLG_KEY_MSG_HELP_ARROW 3

#define MLM_PWD_DLG_LANG_ENG 0

/*-----------------------------------------------------------------------------
                    data declarations
-----------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                    function declarations
-----------------------------------------------------------------------------*/
extern UTF16_T* mlm_pwd_dlg_get_text(UINT16 ui2_lang, UINT16 ui2_key);
extern UINT16 mlm_pwd_dlg_s639_to_langidx(ISO_639_LANG_T s639_lang);
extern VOID mlm_pwd_dlg_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang);

#endif /* _pwd_dlg_mlm_h_ */
