/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.
 * All rights reserved.
 * 
 * Unauthorized use, practice, perform, copy, distribution, reproduction,
 * or disclosure of this information in whole or in part is prohibited.
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: #21 $
 * $Date:   
 * $Author: 
 * $CCRevision: $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/
#ifndef _devdb_mlm_h_
#define _devdb_mlm_h_

/*-----------------------------------------------------------------------------
                   include files
-----------------------------------------------------------------------------*/
#include "u_common.h"

/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
-----------------------------------------------------------------------------*/
#define MLM_DEVDB_TEXT(lang, key) mlm_devdb_get_text(lang, key)

#define MLM_DEVDB_NUM_LANG 3
#define MLM_DEVDB_NUM_KEY 22

#define MLM_DEVDB_KEY_DEV_TYPE_BLU_RAY 0
#define MLM_DEVDB_KEY_DEV_TYPE_CABLE_BOX 1
#define MLM_DEVDB_KEY_DEV_TYPE_COMPUTER 2
#define MLM_DEVDB_KEY_DEV_TYPE_DVD 3
#define MLM_DEVDB_KEY_DEV_TYPE_DVR 4
#define MLM_DEVDB_KEY_DEV_TYPE_GAME 5
#define MLM_DEVDB_KEY_DEV_TYPE_SATELLITE 6
#define MLM_DEVDB_KEY_DEV_TYPE_VCR 7
#define MLM_DEVDB_KEY_DEV_TYPE_AVR_AMPLIFER 8
#define MLM_DEVDB_KEY_DEV_TYPE_SOUND_BAR 9
#define MLM_DEVDB_KEY_DEV_TYPE_BLU_RAY_EX 10
#define MLM_DEVDB_KEY_DEV_TYPE_CABLE_BOX_EX 11
#define MLM_DEVDB_KEY_DEV_TYPE_COMPUTER_EX 12
#define MLM_DEVDB_KEY_DEV_TYPE_DVD_EX 13
#define MLM_DEVDB_KEY_DEV_TYPE_DVR_EX 14
#define MLM_DEVDB_KEY_DEV_TYPE_GAME_EX 15
#define MLM_DEVDB_KEY_DEV_TYPE_SATELLITE_EX 16
#define MLM_DEVDB_KEY_DEV_TYPE_VCR_EX 17
#define MLM_DEVDB_KEY_DEV_TYPE_AVR_AMPLIFER_EX 18
#define MLM_DEVDB_KEY_DEV_TYPE_SOUND_BAR_EX 19
#define MLM_DEVDB_KEY_DEV_TYPE_AVR_AUDIO_RECEIVER 20
#define MLM_DEVDB_KEY_DEV_TYPE_AVR_AMP 21

#define MLM_DEVDB_LANG_ENG 0
#define MLM_DEVDB_LANG_FRE 1
#define MLM_DEVDB_LANG_SPA 2

/*-----------------------------------------------------------------------------
                    data declarations
-----------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                    function declarations
-----------------------------------------------------------------------------*/
extern UTF16_T* mlm_devdb_get_text(UINT16 ui2_lang, UINT16 ui2_key);
extern UINT16 mlm_devdb_s639_to_langidx(ISO_639_LANG_T s639_lang);
extern VOID mlm_devdb_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang);

#endif /* _devdb_mlm_h_ */
