/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.                           
 * All rights reserved.                                                        
 *                                                                             
 * Unauthorized use, practice, perform, copy, distribution, reproduction,      
 * or disclosure of this information in whole or in part is prohibited.        
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: 
 * $Date: 
 * $Author: 
 * $CCRevision: devdb_mlm.c,v $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:                                                                
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                   include files                                               
-----------------------------------------------------------------------------*/
#include "u_common.h"
#include "u_sys_name.h"
#include "c_cl.h"
#include "c_os.h"
#include "amb/a_amb.h"

#ifdef APP_MLMGEN_CUSTOM_LOGIC
#include "res/app_util/mlmgen/a_mlmgen.h"
#endif

/*-----------------------------------------------------------------------------
                    data declarations                                          
-----------------------------------------------------------------------------*/
typedef struct _MLM_DEVDB_TEXT_T
{
    UTF16_T     w2s_dev_type_blu_ray[8];
    UTF16_T     w2s_dev_type_cable_box[14];
    UTF16_T     w2s_dev_type_computer[12];
    UTF16_T     w2s_dev_type_dvd[4];
    UTF16_T     w2s_dev_type_dvr[4];
    UTF16_T     w2s_dev_type_game[6];
    UTF16_T     w2s_dev_type_satellite[10];
    UTF16_T     w2s_dev_type_vcr[4];
    UTF16_T     w2s_dev_type_avr_amplifer[31];
    UTF16_T     w2s_dev_type_sound_bar[16];
    UTF16_T     w2s_dev_type_blu_ray_ex[8];
    UTF16_T     w2s_dev_type_cable_box_ex[14];
    UTF16_T     w2s_dev_type_computer_ex[12];
    UTF16_T     w2s_dev_type_dvd_ex[4];
    UTF16_T     w2s_dev_type_dvr_ex[4];
    UTF16_T     w2s_dev_type_game_ex[6];
    UTF16_T     w2s_dev_type_satellite_ex[10];
    UTF16_T     w2s_dev_type_vcr_ex[4];
    UTF16_T     w2s_dev_type_avr_amplifer_ex[30];
    UTF16_T     w2s_dev_type_sound_bar_ex[16];
    UTF16_T     w2s_dev_type_avr_audio_receiver[16];
    UTF16_T     w2s_dev_type_avr_amp[14];
} MLM_DEVDB_TEXT_T;

static UINT16 ui1_g_mlm_cur_lang_idx = 0xFFFF;
static MLM_DEVDB_TEXT_T t_g_mlm_text;

static UINT8   at_g_compressed_eng[] =
{
    0xcd, 0x8f, 0x4d, 0x0a, 0xc2, 0x40, 0x0c, 0x85, 0xbf, 0xb5,
    0xa7, 0xe8, 0x05, 0xc4, 0x33, 0xd8, 0x11, 0xdc, 0x57, 0x70,
    0x5f, 0xff, 0xa0, 0xd0, 0x5a, 0x29, 0x2a, 0x7a, 0xfb, 0x7e,
    0x33, 0x03, 0x2a, 0x82, 0x6e, 0xdc, 0x98, 0x21, 0x24, 0x93,
    0xf7, 0xf2, 0x92, 0x94, 0xb4, 0x5c, 0x98, 0x32, 0x50, 0x73,
    0x07, 0x82, 0x71, 0x63, 0x6d, 0x4f, 0x41, 0x49, 0xcf, 0x8d,
    0xa7, 0x05, 0xff, 0x1d, 0x27, 0xf9, 0x67, 0xf1, 0xe1, 0x51,
    0x5f, 0xb0, 0xd6, 0x73, 0xac, 0x8c, 0x4b, 0x35, 0x3a, 0x19,
    0xd1, 0x56, 0xe6, 0x91, 0xdd, 0xfa, 0x9a, 0x94, 0x21, 0x2b,
    0x24, 0xde, 0x5c, 0xa5, 0x9d, 0xd5, 0xde, 0x59, 0x95, 0xc8,
    0x56, 0x6f, 0xb8, 0x26, 0xed, 0x09, 0x33, 0xf1, 0x38, 0x2d,
    0xf6, 0x1d, 0xf4, 0xd7, 0x89, 0x59, 0xb9, 0xb7, 0xff, 0xa8,
    0x42, 0xe1, 0xc6, 0xf5, 0x1b, 0x8a, 0xdb, 0xff, 0xe7, 0x65,
    0xbf, 0xde, 0xf5, 0x4d, 0x3b, 0xe3, 0x9f, 0xd5, 0x47, 0x00
};

static UINT8   at_g_compressed_fre[] =
{
    0x73, 0x62, 0xc8, 0x61, 0x28, 0x65, 0xd0, 0x65, 0x28, 0x62,
    0x48, 0x64, 0xa8, 0x64, 0x60, 0x60, 0x70, 0x61, 0x78, 0xc9,
    0x90, 0xcc, 0x90, 0xcf, 0x90, 0xc2, 0x90, 0x0a, 0x14, 0x2f,
    0x62, 0x40, 0x06, 0xfe, 0x40, 0x7e, 0x0a, 0x43, 0x26, 0x43,
    0x1e, 0x50, 0x6d, 0x09, 0x92, 0xbc, 0x0b, 0x43, 0x18, 0x10,
    0x43, 0xe8, 0x20, 0x20, 0xed, 0x05, 0x96, 0x83, 0x80, 0x60,
    0xa8, 0xda, 0x1c, 0x20, 0xcc, 0x04, 0xb3, 0x18, 0x80, 0xaa,
    0x9c, 0xc1, 0xea, 0x82, 0xc0, 0x76, 0xa5, 0x32, 0x14, 0xc0,
    0x4d, 0x53, 0x60, 0x70, 0x04, 0xd2, 0x20, 0x3b, 0xf2, 0x19,
    0xb8, 0x18, 0xf4, 0x81, 0xbc, 0x5c, 0xa0, 0x2c, 0x48, 0x67,
    0x1a, 0x10, 0x27, 0xa3, 0xd8, 0xeb, 0x04, 0xe4, 0x15, 0x01,
    0x61, 0x2a, 0x50, 0x57, 0x0a, 0x98, 0x2c, 0x06, 0xea, 0xca,
    0x83, 0xbb, 0xd6, 0x69, 0xd0, 0xfa, 0x8c, 0x32, 0x7f, 0xe1,
    0x37, 0x9b, 0x01, 0xaf, 0xd9, 0x00, 0x00
};

static UINT8   at_g_compressed_spa[] =
{
    0xcd, 0x8f, 0x31, 0x0e, 0xc2, 0x40, 0x0c, 0x04, 0xa7, 0xe6,
    0x15, 0xf9, 0x00, 0xe2, 0x0d, 0x24, 0x54, 0x94, 0x41, 0xa2,
    0x87, 0xdc, 0x81, 0x40, 0x40, 0xa2, 0x10, 0x0a, 0x9e, 0xcc,
    0x2f, 0x98, 0xbb, 0x08, 0xca, 0x34, 0x34, 0x58, 0xf2, 0xad,
    0xf6, 0xbc, 0x5e, 0xdb, 0x25, 0x17, 0x1e, 0xcc, 0xe9, 0xd9,
    0xf1, 0x04, 0x2a, 0xf1, 0x6c, 0x16, 0x04, 0xa2, 0x6f, 0xe2,
    0x7b, 0x35, 0x31, 0xd7, 0x5a, 0xae, 0x74, 0xea, 0x07, 0x7f,
    0x83, 0x2c, 0x75, 0xc1, 0x8a, 0xad, 0x39, 0x62, 0x2d, 0xae,
    0x55, 0x44, 0x8e, 0xd6, 0x61, 0xa3, 0x62, 0xe0, 0xa5, 0xc3,
    0x49, 0x4c, 0x2e, 0xa8, 0xaa, 0xb2, 0xae, 0x96, 0x37, 0x66,
    0x67, 0x25, 0x79, 0x15, 0x2c, 0xed, 0x0c, 0x2a, 0x5b, 0x66,
    0x2c, 0x64, 0x69, 0x5a, 0xea, 0x3c, 0x98, 0xcd, 0x77, 0xe6,
    0x18, 0xa5, 0xbc, 0xcf, 0x1b, 0x7c, 0x76, 0xbd, 0x5b, 0xbd,
    0xa9, 0x0c, 0x79, 0x72, 0xf9, 0xa7, 0x97, 0xfd, 0x7a, 0xd7,
    0x94, 0x77, 0x8a, 0x29, 0xf7, 0x37, 0x00
};

static UTF16_T*    aw2s_g_txt_tbl[22] =
{
    t_g_mlm_text.w2s_dev_type_blu_ray,
    t_g_mlm_text.w2s_dev_type_cable_box,
    t_g_mlm_text.w2s_dev_type_computer,
    t_g_mlm_text.w2s_dev_type_dvd,
    t_g_mlm_text.w2s_dev_type_dvr,
    t_g_mlm_text.w2s_dev_type_game,
    t_g_mlm_text.w2s_dev_type_satellite,
    t_g_mlm_text.w2s_dev_type_vcr,
    t_g_mlm_text.w2s_dev_type_avr_amplifer,
    t_g_mlm_text.w2s_dev_type_sound_bar,
    t_g_mlm_text.w2s_dev_type_blu_ray_ex,
    t_g_mlm_text.w2s_dev_type_cable_box_ex,
    t_g_mlm_text.w2s_dev_type_computer_ex,
    t_g_mlm_text.w2s_dev_type_dvd_ex,
    t_g_mlm_text.w2s_dev_type_dvr_ex,
    t_g_mlm_text.w2s_dev_type_game_ex,
    t_g_mlm_text.w2s_dev_type_satellite_ex,
    t_g_mlm_text.w2s_dev_type_vcr_ex,
    t_g_mlm_text.w2s_dev_type_avr_amplifer_ex,
    t_g_mlm_text.w2s_dev_type_sound_bar_ex,
    t_g_mlm_text.w2s_dev_type_avr_audio_receiver,
    t_g_mlm_text.w2s_dev_type_avr_amp
};

static UINT8* apui1_g_data_tbl[3] =
{
    at_g_compressed_eng,
    at_g_compressed_fre,
    at_g_compressed_spa
};

static SIZE_T az_g_data_len_tbl[3] =
{
    sizeof(at_g_compressed_eng),
    sizeof(at_g_compressed_fre),
    sizeof(at_g_compressed_spa)
};

static HANDLE_T h_g_lock = NULL_HANDLE;

/*-----------------------------------------------------------------------------
                    function declarations                                          
-----------------------------------------------------------------------------*/
static VOID _mlm_devdb_decompress(UINT16 ui2_lang)
{
    INT32       i4_ret;
    HANDLE_T    h_zip_eng = NULL_HANDLE;
    SIZE_T      z_dest_len = sizeof(MLM_DEVDB_TEXT_T);

    if(ui2_lang >= 3)    /* MLM_DEVDB_LANG_NUM = 3 */
    {
        return;
    }

    do
    {
        i4_ret = c_cl_open_eng(SN_CL_ZIP, NULL, NULL, &h_zip_eng);
        if(i4_ret < 0)
        {
            break;
        }

        i4_ret = c_cl_decompress(h_zip_eng,
                                 apui1_g_data_tbl[ui2_lang],
                                 az_g_data_len_tbl[ui2_lang],
                                 0,
                                 CL_NULL_PARAM_TYPE,
                                 NULL,
                                 &t_g_mlm_text,
                                 &z_dest_len,
                                 NULL);
        if(i4_ret < 0)
        {
            break;
        }

    }while(0);

    if(i4_ret < 0)
    {
        c_memset(&t_g_mlm_text, 0, sizeof(MLM_DEVDB_TEXT_T));
    }

    if(h_zip_eng != (HANDLE_T)NULL)
    {
        c_cl_close(h_zip_eng);
    }
}

static VOID _mlm_devdb_lock(VOID)
{

    /* Acquire lock */
    if(h_g_lock == NULL_HANDLE)
    {
        a_amb_lock();
        if(h_g_lock == NULL_HANDLE)
        {
            c_sema_create(&h_g_lock,
                          X_SEMA_TYPE_MUTEX,
                          X_SEMA_STATE_UNLOCK);
        }
        a_amb_unlock();
    }

    /* Lock */
    if(h_g_lock)
    {
        c_sema_lock(h_g_lock, X_SEMA_OPTION_WAIT);
    }
}

static VOID _mlm_devdb_unlock(VOID)
{
    /* Unlock */
    if(h_g_lock)
    {
        c_sema_unlock(h_g_lock);
    }
}

UTF16_T* mlm_devdb_get_text(UINT16 ui2_lang, UINT16 ui2_key)
{
    if(ui2_lang != ui1_g_mlm_cur_lang_idx)
    {
        _mlm_devdb_lock();
        if(ui2_lang != ui1_g_mlm_cur_lang_idx)
        {
            _mlm_devdb_decompress(ui2_lang);
            ui1_g_mlm_cur_lang_idx = ui2_lang;
        }
        _mlm_devdb_unlock();
    }

#ifdef APP_MLM_CENTER_SUPPORT /* ExcelGen mechanism. */ 
    if (   (aw2s_g_txt_tbl[ui2_key][0] != 0 && aw2s_g_txt_tbl[ui2_key][0] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][1] != 0 && aw2s_g_txt_tbl[ui2_key][1] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][2] != 0 && aw2s_g_txt_tbl[ui2_key][2] == (UTF16_T)L'I')  &&
           (aw2s_g_txt_tbl[ui2_key][3] != 0 && aw2s_g_txt_tbl[ui2_key][3] == (UTF16_T)L'D') )
    {
        extern UTF16_T* mlm_center_get_text_by_hint (CHAR* ps_module_name, UINT16 ui2_lang, UTF16_T* pw2s_hint);

        return mlm_center_get_text_by_hint ("DEVDB", ui2_lang, aw2s_g_txt_tbl[ui2_key]);
    }
#endif

    return aw2s_g_txt_tbl[ui2_key];
}

UINT16 mlm_devdb_s639_to_langidx(ISO_639_LANG_T s639_lang)
{
    UINT16 ui2_lang_idx = 0; 

    if(s639_lang == NULL)
    {
        ui2_lang_idx = 0;
        return ui2_lang_idx;
    }
    if(c_strncmp(s639_lang,"eng",3) ==0)
    {
        ui2_lang_idx = 0; /*MLM_DEVDB_LANG_ENG*/
    }
    else if(c_strncmp(s639_lang,"fre",3) ==0)
    {
        ui2_lang_idx = 1; /*MLM_DEVDB_LANG_FRE*/
    }
    else if(c_strncmp(s639_lang,"spa",3) ==0)
    {
        ui2_lang_idx = 2; /*MLM_DEVDB_LANG_SPA*/
    }
    else
    {
        ui2_lang_idx = 0; /*MLM_DEVDB_LANG_ENG*/
    }
#ifdef MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN
    return MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN("DEVDB", s639_lang, ui2_lang_idx);
#else
    return ui2_lang_idx;
#endif
}
VOID mlm_devdb_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang)
{
    if(s639_lang == NULL)
    {
        return;
    }
    switch(ui2_lang)
    {
        case 0: /*MLM_DEVDB_LANG_ENG*/
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
        case 1: /*MLM_DEVDB_LANG_FRE*/
            c_strncpy(s639_lang,"fre",3);
            s639_lang[3] ='\0';
            break;
        case 2: /*MLM_DEVDB_LANG_SPA*/
            c_strncpy(s639_lang,"spa",3);
            s639_lang[3] ='\0';
            break;
        default:
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
    }
}
