/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.
 * All rights reserved.
 * 
 * Unauthorized use, practice, perform, copy, distribution, reproduction,
 * or disclosure of this information in whole or in part is prohibited.
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: #21 $
 * $Date:   
 * $Author: 
 * $CCRevision: $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/
#ifndef _isl_mlm_h_
#define _isl_mlm_h_

/*-----------------------------------------------------------------------------
                   include files
-----------------------------------------------------------------------------*/
#include "u_common.h"

/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
-----------------------------------------------------------------------------*/
#define MLM_ISL_TEXT(lang, key) mlm_isl_get_text(lang, key)

#define MLM_ISL_NUM_LANG 1
#define MLM_ISL_NUM_KEY 50

#define MLM_ISL_KEY_MSG_TV 0
#define MLM_ISL_KEY_MSG_TV_DTV 1
#define MLM_ISL_KEY_MSG_TV_ATV 2
#define MLM_ISL_KEY_MSG_COMBI 3
#define MLM_ISL_KEY_MSG_COMBI_0 4
#define MLM_ISL_KEY_MSG_COMBI_1 5
#define MLM_ISL_KEY_MSG_COMBI_2 6
#define MLM_ISL_KEY_MSG_COMBI_3 7
#define MLM_ISL_KEY_MSG_CVBS 8
#define MLM_ISL_KEY_MSG_CVBS_0 9
#define MLM_ISL_KEY_MSG_CVBS_1 10
#define MLM_ISL_KEY_MSG_CVBS_2 11
#define MLM_ISL_KEY_MSG_CVBS_3 12
#define MLM_ISL_KEY_MSG_S_VIDEO 13
#define MLM_ISL_KEY_MSG_S_VIDEO_0 14
#define MLM_ISL_KEY_MSG_S_VIDEO_1 15
#define MLM_ISL_KEY_MSG_S_VIDEO_2 16
#define MLM_ISL_KEY_MSG_S_VIDEO_3 17
#define MLM_ISL_KEY_MSG_YPBPR 18
#define MLM_ISL_KEY_MSG_YPBPR_0 19
#define MLM_ISL_KEY_MSG_YPBPR_1 20
#define MLM_ISL_KEY_MSG_YPBPR_2 21
#define MLM_ISL_KEY_MSG_YPBPR_3 22
#define MLM_ISL_KEY_MSG_SCART 23
#define MLM_ISL_KEY_MSG_SCART_0 24
#define MLM_ISL_KEY_MSG_SCART_1 25
#define MLM_ISL_KEY_MSG_SCART_2 26
#define MLM_ISL_KEY_MSG_SCART_3 27
#define MLM_ISL_KEY_MSG_HDMI 28
#define MLM_ISL_KEY_MSG_HDMI_0 29
#define MLM_ISL_KEY_MSG_HDMI_1 30
#define MLM_ISL_KEY_MSG_HDMI_2 31
#define MLM_ISL_KEY_MSG_HDMI_3 32
#define MLM_ISL_KEY_MSG_DVI 33
#define MLM_ISL_KEY_MSG_DVI_0 34
#define MLM_ISL_KEY_MSG_DVI_1 35
#define MLM_ISL_KEY_MSG_DVI_2 36
#define MLM_ISL_KEY_MSG_DVI_3 37
#define MLM_ISL_KEY_MSG_VGA 38
#define MLM_ISL_KEY_MSG_VGA_0 39
#define MLM_ISL_KEY_MSG_VGA_1 40
#define MLM_ISL_KEY_MSG_VGA_2 41
#define MLM_ISL_KEY_MSG_VGA_3 42
#define MLM_ISL_KEY_MSG_DVD_0 43
#define MLM_ISL_KEY_MSG_AUDIO_0 44
#define MLM_ISL_KEY_MSG_MMP 45
#define MLM_ISL_KEY_MSG_MMP_0 46
#define MLM_ISL_KEY_MSG_MMP_1 47
#define MLM_ISL_KEY_MSG_MMP_2 48
#define MLM_ISL_KEY_MSG_UNKNOWN 49

#define MLM_ISL_LANG_ENG 0

/*-----------------------------------------------------------------------------
                    data declarations
-----------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                    function declarations
-----------------------------------------------------------------------------*/
extern UTF16_T* mlm_isl_get_text(UINT16 ui2_lang, UINT16 ui2_key);
extern UINT16 mlm_isl_s639_to_langidx(ISO_639_LANG_T s639_lang);
extern VOID mlm_isl_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang);

#endif /* _isl_mlm_h_ */
