/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.                           
 * All rights reserved.                                                        
 *                                                                             
 * Unauthorized use, practice, perform, copy, distribution, reproduction,      
 * or disclosure of this information in whole or in part is prohibited.        
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: 
 * $Date: 
 * $Author: 
 * $CCRevision: sml_mlm.c,v $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:                                                                
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                   include files                                               
-----------------------------------------------------------------------------*/
#include "u_common.h"
#include "u_sys_name.h"
#include "c_cl.h"
#include "c_os.h"
#include "amb/a_amb.h"

#ifdef APP_MLMGEN_CUSTOM_LOGIC
#include "res/app_util/mlmgen/a_mlmgen.h"
#endif

/*-----------------------------------------------------------------------------
                    data declarations                                          
-----------------------------------------------------------------------------*/
typedef struct _MLM_SML_TEXT_T
{
    UTF16_T     w2s_msg_normal[7];
    UTF16_T     w2s_msg_zoom[10];
    UTF16_T     w2s_msg_panorama[12];
    UTF16_T     w2s_msg_wide[6];
    UTF16_T     w2s_msg_stretch[9];
    UTF16_T     w2s_msg_no_adjust[15];
} MLM_SML_TEXT_T;

static UINT16 ui1_g_mlm_cur_lang_idx = 0xFFFF;
static MLM_SML_TEXT_T t_g_mlm_text;

static UINT8   at_g_compressed_eng[] =
{
    0x4d, 0x8d, 0x4b, 0x0a, 0x80, 0x30, 0x0c, 0x44, 0xdf, 0x51,
    0xbc, 0x8a, 0x17, 0x28, 0x82, 0x0b, 0xc1, 0x5d, 0xac, 0x05,
    0x2d, 0x6a, 0x41, 0xeb, 0xfd, 0x1d, 0x83, 0x0b, 0xb3, 0x08,
    0xf3, 0x65, 0x02, 0x85, 0x93, 0x1d, 0x63, 0x03, 0x46, 0xb1,
    0x22, 0xf6, 0xbf, 0x4e, 0xde, 0xe1, 0x29, 0x93, 0xb3, 0x12,
    0x3f, 0x7d, 0x10, 0x9e, 0x49, 0x8e, 0x7b, 0xaa, 0xfc, 0xa4,
    0x1f, 0x59, 0x5c, 0x09, 0x6a, 0x54, 0x1a, 0x5a, 0x65, 0x32,
    0x37, 0x97, 0x98, 0x31, 0x69, 0xe5, 0x6d, 0x3c, 0x00
};

static UINT8   at_g_compressed_fre[] =
{
    0xf3, 0x63, 0xc8, 0x67, 0x28, 0x62, 0xc8, 0x65, 0x48, 0x64,
    0xc8, 0x61, 0x60, 0x60, 0x88, 0x02, 0xf2, 0xf2, 0x81, 0x3c,
    0x64, 0x10, 0x00, 0x94, 0xcb, 0x03, 0xab, 0x4a, 0x04, 0xca,
    0x64, 0x32, 0x14, 0x32, 0x94, 0x32, 0xa4, 0x02, 0xc5, 0x7d,
    0x80, 0xfc, 0x22, 0x86, 0x74, 0x30, 0xfb, 0x24, 0x43, 0x09,
    0x50, 0xa6, 0x88, 0xe1, 0x25, 0x5c, 0x97, 0x1f, 0x50, 0x47,
    0x1e, 0x83, 0x02, 0x43, 0x10, 0x50, 0x2c, 0x1d, 0x68, 0x76,
    0x22, 0x43, 0x12, 0x90, 0x4c, 0x85, 0xca, 0x02, 0x00, 0x00
};

static UINT8   at_g_compressed_spa[] =
{
    0x3d, 0x8d, 0xcb, 0x0d, 0x80, 0x30, 0x0c, 0x43, 0xdf, 0x28,
    0xac, 0xc2, 0x81, 0x6b, 0xc5, 0x0a, 0x81, 0x22, 0x3e, 0x2a,
    0x45, 0x2a, 0x30, 0x30, 0x9b, 0xe0, 0x06, 0x89, 0x1c, 0xac,
    0x38, 0x7e, 0x56, 0x02, 0x07, 0x85, 0x1d, 0x23, 0x01, 0x2d,
    0xb3, 0x9c, 0x91, 0x89, 0xd2, 0xa8, 0x0c, 0x7a, 0xf7, 0x95,
    0x7a, 0xc4, 0xad, 0x8c, 0x7e, 0xad, 0x6c, 0xd6, 0xbe, 0xb8,
    0xeb, 0x38, 0xb9, 0x94, 0x95, 0xbf, 0x15, 0xa4, 0x8d, 0x98,
    0x8d, 0xdb, 0x33, 0x63, 0xd0, 0x87, 0x89, 0x6f, 0x5e, 0x00
};

static UTF16_T*    aw2s_g_txt_tbl[6] =
{
    t_g_mlm_text.w2s_msg_normal,
    t_g_mlm_text.w2s_msg_zoom,
    t_g_mlm_text.w2s_msg_panorama,
    t_g_mlm_text.w2s_msg_wide,
    t_g_mlm_text.w2s_msg_stretch,
    t_g_mlm_text.w2s_msg_no_adjust
};

static UINT8* apui1_g_data_tbl[3] =
{
    at_g_compressed_eng,
    at_g_compressed_fre,
    at_g_compressed_spa
};

static SIZE_T az_g_data_len_tbl[3] =
{
    sizeof(at_g_compressed_eng),
    sizeof(at_g_compressed_fre),
    sizeof(at_g_compressed_spa)
};

static HANDLE_T h_g_lock = NULL_HANDLE;

/*-----------------------------------------------------------------------------
                    function declarations                                          
-----------------------------------------------------------------------------*/
static VOID _mlm_sml_decompress(UINT16 ui2_lang)
{
    INT32       i4_ret;
    HANDLE_T    h_zip_eng = NULL_HANDLE;
    SIZE_T      z_dest_len = sizeof(MLM_SML_TEXT_T);

    if(ui2_lang >= 3)    /* MLM_SML_LANG_NUM = 3 */
    {
        return;
    }

    do
    {
        i4_ret = c_cl_open_eng(SN_CL_ZIP, NULL, NULL, &h_zip_eng);
        if(i4_ret < 0)
        {
            break;
        }

        i4_ret = c_cl_decompress(h_zip_eng,
                                 apui1_g_data_tbl[ui2_lang],
                                 az_g_data_len_tbl[ui2_lang],
                                 0,
                                 CL_NULL_PARAM_TYPE,
                                 NULL,
                                 &t_g_mlm_text,
                                 &z_dest_len,
                                 NULL);
        if(i4_ret < 0)
        {
            break;
        }

    }while(0);

    if(i4_ret < 0)
    {
        c_memset(&t_g_mlm_text, 0, sizeof(MLM_SML_TEXT_T));
    }

    if(h_zip_eng != (HANDLE_T)NULL)
    {
        c_cl_close(h_zip_eng);
    }
}

static VOID _mlm_sml_lock(VOID)
{

    /* Acquire lock */
    if(h_g_lock == NULL_HANDLE)
    {
        a_amb_lock();
        if(h_g_lock == NULL_HANDLE)
        {
            c_sema_create(&h_g_lock,
                          X_SEMA_TYPE_MUTEX,
                          X_SEMA_STATE_UNLOCK);
        }
        a_amb_unlock();
    }

    /* Lock */
    if(h_g_lock)
    {
        c_sema_lock(h_g_lock, X_SEMA_OPTION_WAIT);
    }
}

static VOID _mlm_sml_unlock(VOID)
{
    /* Unlock */
    if(h_g_lock)
    {
        c_sema_unlock(h_g_lock);
    }
}

UTF16_T* mlm_sml_get_text(UINT16 ui2_lang, UINT16 ui2_key)
{
    if(ui2_lang != ui1_g_mlm_cur_lang_idx)
    {
        _mlm_sml_lock();
        if(ui2_lang != ui1_g_mlm_cur_lang_idx)
        {
            _mlm_sml_decompress(ui2_lang);
            ui1_g_mlm_cur_lang_idx = ui2_lang;
        }
        _mlm_sml_unlock();
    }

#ifdef APP_MLM_CENTER_SUPPORT /* ExcelGen mechanism. */ 
    if (   (aw2s_g_txt_tbl[ui2_key][0] != 0 && aw2s_g_txt_tbl[ui2_key][0] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][1] != 0 && aw2s_g_txt_tbl[ui2_key][1] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][2] != 0 && aw2s_g_txt_tbl[ui2_key][2] == (UTF16_T)L'I')  &&
           (aw2s_g_txt_tbl[ui2_key][3] != 0 && aw2s_g_txt_tbl[ui2_key][3] == (UTF16_T)L'D') )
    {
        extern UTF16_T* mlm_center_get_text_by_hint (CHAR* ps_module_name, UINT16 ui2_lang, UTF16_T* pw2s_hint);

        return mlm_center_get_text_by_hint ("SML", ui2_lang, aw2s_g_txt_tbl[ui2_key]);
    }
#endif

    return aw2s_g_txt_tbl[ui2_key];
}

UINT16 mlm_sml_s639_to_langidx(ISO_639_LANG_T s639_lang)
{
    UINT16 ui2_lang_idx = 0; 

    if(s639_lang == NULL)
    {
        ui2_lang_idx = 0;
        return ui2_lang_idx;
    }
    if(c_strncmp(s639_lang,"eng",3) ==0)
    {
        ui2_lang_idx = 0; /*MLM_SML_LANG_ENG*/
    }
    else if(c_strncmp(s639_lang,"fre",3) ==0)
    {
        ui2_lang_idx = 1; /*MLM_SML_LANG_FRE*/
    }
    else if(c_strncmp(s639_lang,"spa",3) ==0)
    {
        ui2_lang_idx = 2; /*MLM_SML_LANG_SPA*/
    }
    else
    {
        ui2_lang_idx = 0; /*MLM_SML_LANG_ENG*/
    }
#ifdef MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN
    return MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN("SML", s639_lang, ui2_lang_idx);
#else
    return ui2_lang_idx;
#endif
}
VOID mlm_sml_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang)
{
    if(s639_lang == NULL)
    {
        return;
    }
    switch(ui2_lang)
    {
        case 0: /*MLM_SML_LANG_ENG*/
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
        case 1: /*MLM_SML_LANG_FRE*/
            c_strncpy(s639_lang,"fre",3);
            s639_lang[3] ='\0';
            break;
        case 2: /*MLM_SML_LANG_SPA*/
            c_strncpy(s639_lang,"spa",3);
            s639_lang[3] ='\0';
            break;
        default:
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
    }
}
