ifndef PROJECT_ROOT
PROJECT_ROOT := $(word 1, $(subst /project_x/,/project_x /, $(shell pwd)))
$(warning PROJECT_ROOT $(PROJECT_ROOT))
endif

THIS_COMPONENT = Wistron

SRC =

OBJ =

SUB_COMPONENTS = Vizio/Wistron/release_obj

CC_INC +=

#############################################################################
#
# Include the makefile common to all components
#
include $(CUSTOM_ROOT)/common.mak

