#include <vector>
#include <iostream>
#include <cstdlib>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "handler.h"
#include "tv_settings.h"
#include "state.h"
#include "pairing.h"
#include "oobe.h"
#include "uli.h"
#include "pin.h"
#include "system.h"
#include "key_command.h"
#include "events.h"
#include "app.h"
#include "server.h"
#include "airplay.h"
#include "homekit.h"
#include "system_menu.h"
#include "Audio.h"

#include <tv_settings/picture.h>
#include <tv_settings/audio.h>
#include <tv_settings/timers.h>
#include <tv_settings/network.h>
#include <tv_settings/devices.h>
#include <tv_settings/system.h>
#include <tv_settings/admin_and_privacy.h>
#include <tv_settings/cast.h>
#include <tv_settings/channels.h>
#include <tv_settings/closed_captions.h>
#include "uli.h"

#include "rest_event_api.h"
#include "rest_api_variables.h"


VSSP_EVENT p_uri_event[]=
{
        /*** Picture ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/auto_brightness_control"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/ambient_light_sensor"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/backlight"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/tone_mapping"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/luminance"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_aspect"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/brightness"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/contrast"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/tint"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/sharpness"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/picture_mode"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/color_calibration/picture_mode_reference"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/super_resolution"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/edge_enhancement"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/local_contrast"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/peak_luminance"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/progaming_engine/variable_refresh_rate"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/progaming_engine/variable_refresh_rate"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/progaming_engine/game_hdr"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/progaming_engine/game_hdr"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/reduce_noise/contour_smoothing"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_temperature"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/color_calibration/color_temperature_reference"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/calibration_tests/smpte_test_pattern"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/calibration_tests/flat_test_pattern"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/calibration_tests/ramp_test_pattern"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/calibration_tests/uniformity_analyzer_test_pattern"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/calibration_tests/dolby_vision_test_pattern"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/reset_color_tuner"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/header/red"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/header/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/header/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/hue/red"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/hue/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/hue/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/hue/cyan"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/hue/magenta"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/hue/yellow"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/saturation/red"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/saturation/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/saturation/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/saturation/cyan"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/saturation/magenta"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/saturation/yellow"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/brightness/red"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/brightness/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/brightness/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/brightness/cyan"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/brightness/magenta"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/brightness/yellow"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/offset/red"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/offset/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/offset/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/gain/red"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/gain/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/gain/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/color_temperature"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/color_temperature"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/active_full_array"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/active_full_array"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/black_detail"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/black_detail"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/active_led_zones"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/backlight_control"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/backlight_control"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/reduce_judder"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/motion_control/judder_reduction"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/reduce_motion_blur"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/motion_control/motion_blur_reduction"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/clear_action"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/motion_control/clear_action"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/reduce_signal_noise"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/reduce_noise/signal_noise"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/reduce_block_noise"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/advanced_picture/reduce_noise/block_noise"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/progaming_engine/game_low_latency"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/progaming_engine/game_low_latency"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/film_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/color_space"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/gamma"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/advanced_picture/enhanced_viewing_angle"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_mode_edit/save_picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_mode_edit/lock_unlock_picture_mode"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/picture_mode_edit/lock_picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_mode_edit/delete_picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_mode_edit/reset_picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/picture_mode_edit/copy_picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/11_point_balance/*/red"},	//tv_settings/picture/color_calibration/color_tuner/11_point_balance/n_ire/red
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/11_point_balance/*/green"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/color_tuner/11_point_balance/*/blue"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/hdr_backlight"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/more_picture/ultra_color_spectrum"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/lut_selection_normal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/color_calibration/lut_selection_computer"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/full_color_444"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/filmmaker_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/color_space_range"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/size_position/size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/size_position/size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/size_position/position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/size_position/position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/picture/input_picture_settings/hdmi_mode"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/picture/progaming_engine/hdmi_mode"},
	/**** Audio ****/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/tv_speakers"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/volume_control_display"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/surround_sound"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/volume_leveling"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/balance"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/lip_sync"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/digital_audio_out"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/analog_audio_out"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/earc_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/volume"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/mute"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/equalizer/audio_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/equalizer/100_hz"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/equalizer/300_hz"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/equalizer/1k_hz"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/equalizer/3k_hz"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/equalizer/10k_hz"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/delete_audio_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/bluetooth"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/bluetooth_pair"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/dialogue_enhancer"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/bass"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/audio/treble"},
	/*** Timer ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/timers/sleep_timer"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/timers/sleep_timer"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/timers/auto_power_off_timer"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/timers/auto_power_off_timer"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/timers/blank_screen"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/timers/blank_screen"},
	/*** Network ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/connection_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/connection_status"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/current_ssid_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/dhcp_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/ip_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/subnet_mask"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/default_gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/wireless_access_points"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/network/wifi_networks"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/current_access_point"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/dhcp"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/ip_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/subnet_mask"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/default_gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/pref_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/alt_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/rj45_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/manual_setup/wireless_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/start_ap_search"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/stop_ap_search"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/set_wifi_password"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/network/wifi_password_entry"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/hidden_network"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/hidden_network_info/name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/hidden_network_info/password"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/test_connection"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/test_connection_results"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/retest"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/dhcp"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/ip_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/subnet_mask"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/default_gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/pref_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/alt_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/rj45_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/test_connection/manual_setup/wireless_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/wired_connection"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/forget_saved_network"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/terms_and_conditions"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/viewing_data"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/connection_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ssid"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/security_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ip_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/default_gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/subnet_mask"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/pref_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/alt_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/rssi"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/rj45_mac"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/wlan_mac"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/wifi_module"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ipv6_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ipv6_gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ipv6_prefix_len"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ipv6_pref_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/network/network_information/ipv6_alt_dns_server"},
	/*** Device ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/cast"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/cast/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/hdmi1"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/hdmi1/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/hdmi2"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/hdmi2/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/hdmi3"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/hdmi3/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/hdmi4"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/hdmi4/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/hdmi5"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/hdmi5/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/comp"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name/comp/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/current_input"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/input_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/hdmi_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/hdmi_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/hdmi_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/hdmi_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/hdmi_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/full_chrome/hdmi1"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/full_chrome/hdmi2"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/full_chrome/hdmi3"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/full_chrome/hdmi4"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/full_chrome/hdmi5"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/tuner"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/name_input/vga"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/auto_size_position"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/cast/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/comp/name_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/comp/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/tuner/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/tuner/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/tuner/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/tuner/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/tuner/hide_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/current_inputs"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi1/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi2/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi3/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi4/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/hdmi5/picture_position/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/comp/picture_size/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/comp/picture_size/vertical"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/comp/picture_position/horizontal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/devices/comp/picture_position/vertical"},
	/*** System ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/cast_name"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/tv_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/serial_number"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/serial_number"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/model_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/version"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/firmware"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/chromium_version"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/conjure"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/scpl_version"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/sc_config"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/amazon_version"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/amazon_version"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/vrr"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/vrr"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/country"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/country"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/cast_version"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/source_type"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/source_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/resolution"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/vertical_frequency"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/hdr"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/audio_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/frc_version"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/netflix_esn"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/netflix_esn2"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/netflix_esn_native"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/ssid"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/security_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/ip_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/subnet_mask"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/preferred_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/alternate_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/download_speed"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/wifi_signal_strength"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/rssi"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/wifi_channel"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/rj45_mac_address"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/rj45_mac_address"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/wlan_mac_address"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/wlan_mac_address"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/bt_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/esn"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/uli_information/esn"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/sv"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/reg"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/netflix_esn_native"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/uli_information/netflix_esn_native"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/np"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/uid"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/dev_id"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/prov_id"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/uli_information/da"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/service_reset"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/soft_power_cycle"},    /*Mapping URI to the previous URI*/
    { 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/dlm_reset"},
    { 0 ,  VSSP_MODEL_MAP1	    ,(char*)"tv_settings/admin_and_privacy/dlm_reset"},	  /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/service_check"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/check_for_update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/local_time_settings/use_internet_time"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/local_time_settings/date_time"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/local_time_settings/timezone"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/time/time_zone"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/time/automatic_time"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/local_time_settings/daylight_savings_time"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/local_time_settings/time_format"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/time/time_format"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/local_time_settings/country"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/country"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/menu_language"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/cec/cec_function"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/cec/device_discovery"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/cec/device_discovery_results"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/power_indicator"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/power_indicator"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/usb_power"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/usb_power"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/factory_reset"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/factory_reset"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/vizio_privacy_policy"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/vizio_privacy_policy"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/smart_interactivity"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/viewing_data"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/store_demo"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/store_demo"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/advertising/limit_ad_tracking"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/advertising/limit_ad_tracking"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/advertising/tvad_id_reset"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/advertising/tvad_id_reset"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/advertising/ad_replacement"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/advertising/ad_replacement"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tuner_information/physical_channel"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tuner_information/frequency"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tuner_information/modulation"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tuner_information/status"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tuner_information/signal_strength"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tuner_information/name"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/admin_and_privacy/system_information/channel_information/tuner_brand"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/country"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_from_input_list"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_input/tv"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_input/comp"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_input/hdmi1"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_input/hdmi2"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_input/hdmi3"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/hide_input/hdmi4"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/energy_saving_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/oled_panel"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/oled_panel/screen_refresher"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/oled_panel/pixel_shift"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/voice_remote"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/power_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/aspect_ratio"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/cast_name"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/tv_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/reset_and_admin/system_pin"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/system/system_pin"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/series"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/size"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/accessibility/talkback"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/accessibility/talkback"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/accessibility/speech_rate"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/accessibility/zoom_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/accessibility/video_description"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/audio_type_out"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/network_information/wifi_module"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/system_information/tv_information/airplay_version"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/system/input_at_power_on"},
	/*** admin_and_privacy ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/frame_rate"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/audio_in"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/audio_out"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/bluetooth_version"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/tv_information/display_hours"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/wifi_network"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/id_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/connection_type"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/wifi_security"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/remote_information/remote_status"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/remote_information/remote_firmware"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/remote_information/remote_serial_number"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/remote_information/bluetooth_firmware"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/remote_information/bluetooth_mac_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/scpl"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/airplay"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/airplay_internal"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/appletv"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/hbomax"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/castcore"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/cobalt"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/dai"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/application_information/vizio_ndk"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/uli_information/country"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/uli_information/display_hours"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/support_code"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/ipv6_address"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/ipv6_gateway"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/ipv6_prefix_len"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/ipv6_preferred_dns_server"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/admin_and_privacy/system_information/network_information/ipv6_alternate_dns_server"},
	/*** Cast ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/device_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/serial_device_id"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/google_privacy_policy"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/tos_accepted"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/soft_ap_config"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/start_soft_ap"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/stop_soft_ap"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/soft_ap_status"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/soft_ap_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/state"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/session_device_id"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/google_cast_id"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/cast/google_cast_cd"},
	/*** Channel Scan ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/auto_channel_scan"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/analog"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/digital"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/percent_complete"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/find_new_channel"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/analog_audio"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/digital_language"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/channels/digital_audio"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/locks"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/channel_locks"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_y"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_y/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_y7"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_y7/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_y7/fv"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_g"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_g/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_pg"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_pg/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_pg/d"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_pg/s"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_pg/l"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_pg/v"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_14"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_14/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_14/d"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_14/s"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_14/l"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_14/v"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_ma"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_ma/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_ma/s"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_ma/l"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_tv/tv_ma/v"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie/all"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie/g"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie/pg"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie/pg_13"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie/r"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/usa_movie/nc_17"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english/c"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english/c_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english/g"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english/pg"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english/14_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_english/18_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_french"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_french/g"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_french/8_ans_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_french/13_ans_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_french/16_ans_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/canadian_french/18_ans_plus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/drrt"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/drrt/*"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/drrt/*/*"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/block_unrated_shows"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/reset"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/channels/parental_controls/reset_locks"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/current_channel"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/skip_channel/*"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/skip_channel/*/name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/skip_channel/*/state"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/channel_locks/*"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/channel_locks/*/name"}, //tv_settings/channels/parental_controls/channel_locks/channel_<NUM>/name
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/parental_controls/channel_locks/*/state"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/channels/cancel_channel_scan"},
	/*** Close Caption ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/closed_captions_enabled"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/accessibility/closed_captions/closed_captions_enabled"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/analog_closed_captions"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_closed_captions"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/accessibility/closed_captions/digital_style"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/text_style"},
	{ 0 ,  VSSP_MODEL_MAP1      ,(char*)"tv_settings/accessibility/closed_captions/digital_style/text_style"},    /*Mapping URI to the previous URI*/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/text_size"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/text_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/text_opacity"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/text_edges"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/text_edges_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/background_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/background_opacity"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/window_color"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"tv_settings/closed_captions/digital_style/window_opacity"},
	/*** state ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/deviceinfo"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/cast"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/hdmi1"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/hdmi2"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/hdmi3"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/hdmi4"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/hdmi5"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/comp"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/name_input/vga"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/audio/is_sound_bar_connected"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/acr/whatson"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/cec/hdmi1"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/cec/hdmi2"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/cec/hdmi3"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/cec/hdmi4"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/cec/hdmi5"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/device/currentstate"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/device/power_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/cast"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/hdmi1"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/hdmi2"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/hdmi3"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/hdmi4"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/hdmi5"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/comp"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/devices/vga"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/tuner/channel_settings"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/tuner/all_channel_settings"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/tuner/drrt_name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/tuner/drrt_all_settings"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"state/tuner/drrt_settings"},
	/*** pairing ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/bt/getauthtoken"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/bt/status"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/bt/rssimeter"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/start"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/pair"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/unpair"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/correct_challenge_response"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/cancel"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/bt/dev_info"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pairing/stop"},
	/*** oobe ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"oobe/currentstate"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"oobe/is_complete"},
	/*** uli ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/register"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/is_device_registered"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/is_owner_registered"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/is_updating"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/available_update_info"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/start_update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/update_status"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"uli/update_time"},
	/*** pin ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pin/confirm_pin"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pin/set_pin"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pin/is_pin_default"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"pin/is_pin_confirmed"},
	/* system */
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/displayInfo"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/restVersion"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/config/update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/decrypt"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/assets/stage"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/assets/update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/acr/state"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/ready"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/pong"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/systemInfo"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/capabilities"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/deviceInputs"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/stage"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/network_time"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/binaries/version"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/native_power_function"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/current_inputs"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/is_composite"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/input/list"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/input/current_input"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/identify"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/input/name"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/input/visible"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/airplay/user_settings_path"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/binaries/stage"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/uninstall"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/remote_logging"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/test/check_for_update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/picture/picture_mode"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/cec"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system/cec/list"},

	/*** key_command ***/
	{0 ,  VSSP_MODEL_ORIGINAL   ,(char*)"key_command/"},
	/*** app ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/launch"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/current"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/is_in_ambient"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/exit"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/tts/enabled"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/tts/play"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/zoom/enabled"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/zoom/focus"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/splash/show"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/splash/hide"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/key/delegate"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/menu/show"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/menu/hide"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/input/create"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/input/metadata"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/input/update"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/input/delete"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"app/tts/cancel"},
	/*** server ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"server/ready"},
	/*** airplay ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"airplay/property"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"airplay/action"},
	/*** homekit ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"homekit/pairing_status"},
	/*** system_menu ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"system_menu/enabled"},
	/*** audio ***/
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"audio/volume/level"},
	{ 0 ,  VSSP_MODEL_ORIGINAL  ,(char*)"audio/volume/mute"},
};

//for searching ,we use this to map the offset => handler offset
VSSP_HEAD_URI gp_main_uri[]=
{
	{0,0,"tv_settings/picture",picture_handler},
	{0,0,"tv_settings/audio",tv_settings_audio_handler},
	{0,0,"tv_settings/timer",timers_handler},
	{0,0,"tv_settings/network",network_handler},
	{0,0,"tv_settings/devices",devices_handler},
	{0,0,"tv_settings/system",tv_settings_system_handler},
	{0,0,"tv_settings/admin_and_privacy",tv_settings_admin_and_privacy_handler},
	{0,0,"tv_settings/cast",cast_handler},
	{0,0,"tv_settings/channel",channels_handler},
	{0,0,"tv_settings/closed_captions",closed_captions_handler},
	{0,0,"state",state_handler},
	{0,0,"pairing",pairing_handler},
	{0,0,"oobe",oobe_handler},
	{0,0,"uli",uli_handler},
	{0,0,"pin",pin_handler},
	{0,0,"system",system_handler},
	{0,0,"key_command",key_command_handler},
	{0,0,"app",app_handler},
	{0,0,"server",server_handler},
	{0,0,"airplay",airplay_handler},
	{0,0,"homekit",homekit_handler},
	{0,0,"system_menu",system_menu_handler},
	{0,0,"audio",audio_handler},
};


//for mapping model ,we use this for map different url to one
MAPPING_RULES gp_mp_rules[]=
{
	{//admin&privacy
		"tv_settings/system/system_information/tuner_information/",
		"tv_settings/admin_and_privacy/system_information/channel_information/"
	},
	{//admin&privacy
		"tv_settings/system/",
		"tv_settings/admin_and_privacy/"
	},
	{//network
		"tv_settings/network/manual_setup/",
		"tv_settings/network/manual_setup_info/",
	},
	{//picture
		"tv_settings/picture/color_calibration/color_tuner/11_point_balance/",
		"tv_settings/picture/advanced_picture/color_calibration/white_balance_tuner/20_point_balance/",
	},
	{//picture
		"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/header/",
		"tv_settings/picture/advanced_picture/color_calibration/color_tuner/primary_color/",
	},
	{//picture
		"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/",
		"tv_settings/picture/advanced_picture/color_calibration/color_tuner/",
	},
	{//picture
		"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/",
		"tv_settings/picture/advanced_picture/color_calibration/white_balance_tuner/",
	},
	{//picture
		"tv_settings/picture/color_calibration/color_tuner/color_tuner_table/offset/",
		"tv_settings/picture/advanced_picture/color_calibration/white_balance_tuner/offset/",
	},
	{//picture
		"tv_settings/picture/more_picture/",
		"tv_settings/picture/advanced_picture/"
	},
	{//picture
		"tv_settings/picture/",
		"tv_settings/picture/advanced_picture/"
	},
	{//close caption
		"tv_settings/closed_captions/",
		"tv_settings/accessibility/closed_captions/",
	},
	{//system
		"tv_settings/system/accessibility/",
		"tv_settings/accessibility/",
	},
	{//time
		"tv_settings/system/local_time_settings/",
		"tv_settings/system/time/",
	},
};


int g_uri_number = sizeof(p_uri_event)/sizeof(VSSP_EVENT);    //the uri number
int g_header_number = sizeof(gp_main_uri)/sizeof(VSSP_HEAD_URI);    //the header number
int g_map_rules_number = sizeof(gp_mp_rules)/sizeof(MAPPING_RULES);    //the header number


