/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This file was automatically generated by the Convert tool
 * It should not be modified by hand.
 */
#ifndef _MTKTVAPI_CONFIG_MSG_CUSTOM_H_
#define _MTKTVAPI_CONFIG_MSG_CUSTOM_H_
#endif
