/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This file was automatically generated by the Convert tool
 * It should not be modified by hand.
 */
#ifndef _MTKTVAPI_CONFIG_TYPE_CUSTOM_H_
#define _MTKTVAPI_CONFIG_TYPE_CUSTOM_H_

#ifdef APP_C4TV_SUPPORT
#define CFG_MISC_SHOW_SPLASH               CFG_GRP_MISC_PREFIX"show_splash"    /**<        */
#define CFG_MISC_UNBLANK_SCREEN            CFG_GRP_MISC_PREFIX"unblank_screen"    /**<        */
#endif

#define CFG_MISC_POWER_MODE                CFG_GRP_MISC_PREFIX"power_mode"    /**<        */

#endif
