/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.
 * All rights reserved.
 * 
 * Unauthorized use, practice, perform, copy, distribution, reproduction,
 * or disclosure of this information in whole or in part is prohibited.
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: #21 $
 * $Date:   
 * $Author: 
 * $CCRevision: $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/
#ifndef _fac_mlm_h_
#define _fac_mlm_h_

/*-----------------------------------------------------------------------------
                   include files
-----------------------------------------------------------------------------*/
#include "u_common.h"

/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
-----------------------------------------------------------------------------*/
#define MLM_FAC_TEXT(lang, key) mlm_fac_get_text(lang, key)

#define MLM_FAC_NUM_LANG 3
#define MLM_FAC_NUM_KEY 169

#define MLM_FAC_KEY_MSG_BRAND 0
#define MLM_FAC_KEY_MSG_MAIN_MCU_VER 1
#define MLM_FAC_KEY_MSG_BOOT_LOADER_VER 2
#define MLM_FAC_KEY_MSG_EEPROM_VER 3
#define MLM_FAC_KEY_MSG_SUB_MCU_VER 4
#define MLM_FAC_KEY_MSG_DATE 5
#define MLM_FAC_KEY_MSG_MODEL_NAME 6
#define MLM_FAC_KEY_MSG_SCALER 7
#define MLM_FAC_KEY_MSG_TUNER_TYPE 8
#define MLM_FAC_KEY_MSG_PANEL_TYPE 9
#define MLM_FAC_KEY_MSG_CURRENT_SOURCE 10
#define MLM_FAC_KEY_MSG_AUTO_COLOR 11
#define MLM_FAC_KEY_MSG_ADC_R_GAIN 12
#define MLM_FAC_KEY_MSG_ADC_G_GAIN 13
#define MLM_FAC_KEY_MSG_ADC_B_GAIN 14
#define MLM_FAC_KEY_MSG_ADC_R_OFFSET 15
#define MLM_FAC_KEY_MSG_ADC_G_OFFSET 16
#define MLM_FAC_KEY_MSG_ADC_B_OFFSET 17
#define MLM_FAC_KEY_MSG_COLOR_TEMP 18
#define MLM_FAC_KEY_MSG_SCALER_R_GAIN 19
#define MLM_FAC_KEY_MSG_SCALER_G_GAIN 20
#define MLM_FAC_KEY_MSG_SCALER_B_GAIN 21
#define MLM_FAC_KEY_MSG_SCALER_R_OFFSET 22
#define MLM_FAC_KEY_MSG_SCALER_G_OFFSET 23
#define MLM_FAC_KEY_MSG_SCALER_B_OFFSET 24
#define MLM_FAC_KEY_MSG_CLR_COPY 25
#define MLM_FAC_KEY_MSG_BURN_IN 26
#define MLM_FAC_KEY_MSG_EEPROM_INIT 27
#define MLM_FAC_KEY_MSG_HDMI_EDID_LOAD 28
#define MLM_FAC_KEY_MSG_BACK_LIT_TIME 29
#define MLM_FAC_KEY_MSG_BACKLIGHT_MAX 30
#define MLM_FAC_KEY_MSG_BACKLIGHT_MIN 31
#define MLM_FAC_KEY_MSG_LANGUAGE 32
#define MLM_FAC_KEY_MSG_RESET 33
#define MLM_FAC_KEY_MSG_VGA_SWITCH 34
#define MLM_FAC_KEY_MSG_VCOM 35
#define MLM_FAC_KEY_MSG_WB_PAT 36
#define MLM_FAC_KEY_MSG_EXIT 37
#define MLM_FAC_KEY_MSG_YES 38
#define MLM_FAC_KEY_MSG_NO 39
#define MLM_FAC_KEY_MSG_RETURN 40
#define MLM_FAC_KEY_MSG_BRAND_NAME 41
#define MLM_FAC_KEY_MSG_SCALER_NAME 42
#define MLM_FAC_KEY_MSG_DONE 43
#define MLM_FAC_KEY_MSG_FAIL 44
#define MLM_FAC_KEY_MSG_COOL 45
#define MLM_FAC_KEY_MSG_WARM 46
#define MLM_FAC_KEY_MSG_STANDARD 47
#define MLM_FAC_KEY_MSG_USER 48
#define MLM_FAC_KEY_MSG_PRESS 49
#define MLM_FAC_KEY_MSG_ENTER_FAC 50
#define MLM_FAC_KEY_MSG_LEAVE_FAC 51
#define MLM_FAC_KEY_MSG_TEST_MODE_ON 52
#define MLM_FAC_KEY_MSG_VIRGIN_MODE 53
#define MLM_FAC_KEY_MSG_VIRGIN_MODE_OFF 54
#define MLM_FAC_KEY_MSG_ORT_MODE_ON 55
#define MLM_FAC_KEY_MSG_ORT_MODE_OFF 56
#define MLM_FAC_KEY_MSG_AV_RESET 57
#define MLM_FAC_KEY_MSG_BRIGHT_50P 58
#define MLM_FAC_KEY_MSG_BRIGHT_100P 59
#define MLM_FAC_KEY_MSG_CONTRAST_50P 60
#define MLM_FAC_KEY_MSG_CONTRAST_100P 61
#define MLM_FAC_KEY_MSG_PIC_MODE_USER 62
#define MLM_FAC_KEY_MSG_PIC_MODE_DYNAMIC 63
#define MLM_FAC_KEY_MSG_PIC_MODE_STANDARD 64
#define MLM_FAC_KEY_MSG_PIC_MODE_MILD 65
#define MLM_FAC_KEY_MSG_PIC_MODE_MOVIE 66
#define MLM_FAC_KEY_MSG_PIC_MODE_ECO 67
#define MLM_FAC_KEY_MSG_WB_NORMAL 68
#define MLM_FAC_KEY_MSG_WB_WARM 69
#define MLM_FAC_KEY_MSG_WB_COOL 70
#define MLM_FAC_KEY_MSG_WB_USER 71
#define MLM_FAC_KEY_MSG_SOUND_MODE_STEREO 72
#define MLM_FAC_KEY_MSG_AVL_OFF 73
#define MLM_FAC_KEY_MSG_BALANCE_RIGHT 74
#define MLM_FAC_KEY_MSG_BALANCE_LEFT 75
#define MLM_FAC_KEY_MSG_VOLUME_100P 76
#define MLM_FAC_KEY_MSG_VOLUME_50P 77
#define MLM_FAC_KEY_MSG_VOLUME_25P 78
#define MLM_FAC_KEY_MSG_AUTO_COLOR_PROCESS 79
#define MLM_FAC_KEY_MSG_AUTO_COLOR_DONE 80
#define MLM_FAC_KEY_MSG_AUTO_COLOR_FAIL 81
#define MLM_FAC_KEY_MSG_SET_ALL_PM 82
#define MLM_FAC_KEY_MSG_SET_TO_FM 83
#define MLM_FAC_KEY_MSG_EDID 84
#define MLM_FAC_KEY_MSG_UART 85
#define MLM_FAC_KEY_MSG_EDID_WP_EN 86
#define MLM_FAC_KEY_MSG_EDID_WP_DIS 87
#define MLM_FAC_KEY_MSG_URC_VGA_SWITCH 88
#define MLM_FAC_KEY_MSG_TEST_MODE 89
#define MLM_FAC_KEY_MSG_BACKLIGHT_50 90
#define MLM_FAC_KEY_MSG_BACKLIGHT_100 91
#define MLM_FAC_KEY_MSG_PRESET_CH 92
#define MLM_FAC_KEY_MSG_BURN_IN_ON 93
#define MLM_FAC_KEY_MSG_BURN_IN_OFF 94
#define MLM_FAC_KEY_MSG_RESET_FINISH 95
#define MLM_FAC_KEY_MSG_SURROUND_ON 96
#define MLM_FAC_KEY_MSG_SURROUND_OFF 97
#define MLM_FAC_KEY_MSG_DCR_ON 98
#define MLM_FAC_KEY_MSG_DCR_OFF 99
#define MLM_FAC_KEY_MSG_VOL_MAX 100
#define MLM_FAC_KEY_MSG_VOL_BUZZ 101
#define MLM_FAC_KEY_MSG_PATTERN_RED 102
#define MLM_FAC_KEY_MSG_PATTERN_GREEN 103
#define MLM_FAC_KEY_MSG_PATTERN_BLUE 104
#define MLM_FAC_KEY_MSG_PATTERN_WHITE 105
#define MLM_FAC_KEY_MSG_PATTERN_BLACK 106
#define MLM_FAC_KEY_MSG_PATTERN_OFF 107
#define MLM_FAC_KEY_MSG_AUTO_CONFIG 108
#define MLM_FAC_KEY_MSG_BLK_50P 109
#define MLM_FAC_KEY_MSG_BLK_100P 110
#define MLM_FAC_KEY_MSG_VCOM_VALUE 111
#define MLM_FAC_KEY_MSG_VCOM_STORE 112
#define MLM_FAC_KEY_MSG_GAMMA1 113
#define MLM_FAC_KEY_MSG_GAMMA2 114
#define MLM_FAC_KEY_MSG_GAMMA3 115
#define MLM_FAC_KEY_MSG_GAMMA4 116
#define MLM_FAC_KEY_MSG_GAMMA5 117
#define MLM_FAC_KEY_MSG_GAMMA6 118
#define MLM_FAC_KEY_MSG_GAMMA7 119
#define MLM_FAC_KEY_MSG_GAMMA8 120
#define MLM_FAC_KEY_MSG_TCON_EXIT 121
#define MLM_FAC_KEY_MSG_ANTENNA 122
#define MLM_FAC_KEY_MSG_CABLE 123
#define MLM_FAC_KEY_MSG_LED_OFF 124
#define MLM_FAC_KEY_MSG_LED_ON 125
#define MLM_FAC_KEY_MSG_PIC_MODE_HOME 126
#define MLM_FAC_KEY_MSG_PIC_MODE_GAME 127
#define MLM_FAC_KEY_MSG_PIC_MODE_RETAIL 128
#define MLM_FAC_KEY_MSG_PIC_MODE_PHOTO 129
#define MLM_FAC_KEY_MSG_PIC_MODE_CUSTOM 130
#define MLM_FAC_KEY_MSG_OAD_ENABLE 131
#define MLM_FAC_KEY_MSG_DUMP_CH_INFO 132
#define MLM_FAC_KEY_MSG_FLIP 133
#define MLM_FAC_KEY_MSG_MIRROR 134
#define MLM_FAC_KEY_MSG_EEPROM_DUMP 135
#define MLM_FAC_KEY_MSG_AUD_SRS_BYPASS 136
#define MLM_FAC_KEY_MSG_PIC_STANDARD 137
#define MLM_FAC_KEY_MSG_PIC_MOVIE 138
#define MLM_FAC_KEY_MSG_PIC_GAME 139
#define MLM_FAC_KEY_MSG_PIC_VIVID 140
#define MLM_FAC_KEY_MSG_PIC_FOOTBALL 141
#define MLM_FAC_KEY_MSG_PIC_GOLF 142
#define MLM_FAC_KEY_MSG_PIC_BASKETBALL 143
#define MLM_FAC_KEY_MSG_PIC_BASEBALL 144
#define MLM_FAC_KEY_MSG_PIC_CUSTOM 145
#define MLM_FAC_KEY_MSG_NO_USB 146
#define MLM_FAC_KEY_MSG_HDMI_PORT_NUM 147
#define MLM_FAC_KEY_MSG_INSTALL_ULPK 148
#define MLM_FAC_KEY_MSG_QUERY_ULPK 149
#define MLM_FAC_KEY_MSG_ERASE_ULPK 150
#define MLM_FAC_KEY_MSG_ARC_OFF 151
#define MLM_FAC_KEY_MSG_ARC_ON 152
#define MLM_FAC_KEY_MSG_LSR_OFF 153
#define MLM_FAC_KEY_MSG_LSR_ON 154
#define MLM_FAC_KEY_MSG_3D2D_3D 155
#define MLM_FAC_KEY_MSG_3D2D_2D 156
#define MLM_FAC_KEY_MSG_NOT_SUPPORT 157
#define MLM_FAC_KEY_MSG_ITEM_STD 158
#define MLM_FAC_KEY_MSG_ITEM_BRIGHT_ROOM 159
#define MLM_FAC_KEY_MSG_ITEM_DARK_ROOM 160
#define MLM_FAC_KEY_MSG_ITEM_RETAIL 161
#define MLM_FAC_KEY_MSG_ITEM_GAME 162
#define MLM_FAC_KEY_MSG_ITEM_COMPURER 163
#define MLM_FAC_KEY_MSG_PQ_VER 164
#define MLM_FAC_KEY_MSG_AQ_VER 165
#define MLM_FAC_KEY_MSG_WINDOW_PATTERN 166
#define MLM_FAC_KEY_MSG_ON 167
#define MLM_FAC_KEY_MSG_OFF 168

#define MLM_FAC_LANG_ENG 0
#define MLM_FAC_LANG_FRE 1
#define MLM_FAC_LANG_SPA 2

/*-----------------------------------------------------------------------------
                    data declarations
-----------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                    function declarations
-----------------------------------------------------------------------------*/
extern UTF16_T* mlm_fac_get_text(UINT16 ui2_lang, UINT16 ui2_key);
extern UINT16 mlm_fac_s639_to_langidx(ISO_639_LANG_T s639_lang);
extern VOID mlm_fac_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang);

#endif /* _fac_mlm_h_ */
