#ifndef _GLUE_LAYER_COMM_H_
#define _GLUE_LAYER_COMM_H_

#include "u_common.h"
//#include "factory/a_factory.h"
//#include "gluelayer_tbl.h"

#define     GLUELR_OK               (0)
#define     GLUELR_INV_ARG          (-1)
#define     GLUELR_FAIL             (-2)
#define     GLUELR_NO_DATA          (-3)

#define     GLUELAYER_CMD_GRP_MACRO         ((UINT8)0x01)
#define     GLUELAYER_CMD_GRP_API           ((UINT8)0x02)
#define     GLUELAYER_CMD_GRP_STRUCT        ((UINT8)0x03)

#define     GLUELAYER_CMD_GET_GRP_ID(_cmd)  ((T_GLUELAYER_CMD_TYPE)(((UINT32)_cmd & 0xFF000000)>>24))
#define     GLUELAYER_CMD_GET_CMD_ID(_cmd)  ((T_GLUELAYER_CMD_TYPE)((UINT32)_cmd & 0x00FFFFFF))
#define     GLUELAYER_CMD_MAK(_grp, _cmd)   ((T_GLUELAYER_CMD_TYPE)((UINT32)(((_grp<<24)&0xFF000000)|(_cmd&0x00FFFFFF))))

typedef UINT32      T_GLUELAYER_CMD_TYPE;

typedef struct {
    CHAR    s_name[128];
    UINT32 ui4_cmd;
    VOID *pv_data;    
} T_CMD_DATA_MAP;

typedef struct {
    CHAR    s_name[128];
    UINT32 ui4_cmd;
    VOID **pv_data;    
} T_CMD_DATA_MAP_API;

/* GLUELAYER_CMD_GRP_MACRO */
typedef enum {
/* VALUE MACRO */
    GLUELAYER_CMD_M_FACTORYR_OK = 1,
    GLUELAYER_CMD_M_FACTORYR_NOT_INIT     ,
    GLUELAYER_CMD_M_FACTORYR_OUT_OF_MEMORY,
    GLUELAYER_CMD_M_FACTORYR_FAIL         ,
    GLUELAYER_CMD_M_FACTORY_COMMAND_HEADER,
    GLUELAYER_CMD_M_FACTORY_COMMAND_TAIL  ,
    GLUELAYER_CMD_M_FACTORY_COMMAND_LENGTH,
    GLUELAYER_CMD_M_FACTORY_DATA_TRANSFER_MODE_LENGTH,   
                                            
    GLUELAYER_CMD_M_IDX_CLR_FAC_GAIN_R  ,
    GLUELAYER_CMD_M_IDX_CLR_FAC_GAIN_G  ,
    GLUELAYER_CMD_M_IDX_CLR_FAC_GAIN_B  ,
    GLUELAYER_CMD_M_IDX_CLR_FAC_OFFSET_R,
    GLUELAYER_CMD_M_IDX_CLR_FAC_OFFSET_G,
    GLUELAYER_CMD_M_IDX_CLR_FAC_OFFSET_B,
                                            
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_0,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_1,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_2,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_3,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_4,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_5,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_6,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_7,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_8,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_9,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_10,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_11,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_12,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_13,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_14,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_15,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_16,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_17,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_18,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_19,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_20,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_21,
                                            
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_2_0,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_2_1,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_2_2,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_2_3,
                                           
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_4_0,
    GLUELAYER_CMD_M_IDX_FAC_CUST_RESERV_4_1,
                                            
    GLUELAYER_CMD_M_IDX_FAC_CMD_RESERV,
                                                              
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_OFFSET_MAGIC,
    GLUELAYER_CMD_M_EEP_OFFSET_EEP2_START,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CUST_SN,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CUST_AGING_OP_TIMER,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CUST_AGING_POWER_ON_MINS ,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CUST_AGING_POWER_ON_TIMES,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CUST_PN ,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CUST_MBN,
    GLUELAYER_CMD_M_EEP_GAMMA_END,
    GLUELAYER_CMD_M_EEP_WB_BACKUP,
    GLUELAYER_CMD_M_EEP_WB_MAGIC,
                                                     
    /* Group Video. */                                   
    GLUELAYER_CMD_M_APP_CFG_RECID_VID_FAC_GAIN_R,
    GLUELAYER_CMD_M_APP_CFG_RECID_VID_FAC_GAIN_G,
    GLUELAYER_CMD_M_APP_CFG_RECID_VID_FAC_GAIN_B,
    GLUELAYER_CMD_M_APP_CFG_RECID_VID_FAC_OFFSET_R,
    GLUELAYER_CMD_M_APP_CFG_RECID_VID_FAC_OFFSET_G,
    GLUELAYER_CMD_M_APP_CFG_RECID_VID_FAC_OFFSET_B,
    GLUELAYER_CMD_M_APP_CFG_RECID_FAC_CMD_RESERV,
                                                     
    /* Group Factory. */                                 
    GLUELAYER_CMD_M_APP_CFG_RECID_FAC_CUST_RESERV_0,        
    GLUELAYER_CMD_M_APP_CFG_RECID_FAC_CUST_RESERV_1,        
    GLUELAYER_CMD_M_APP_CFG_RECID_FAC_CUST_RESERV_2,        
    GLUELAYER_CMD_M_APP_CFG_RECID_FAC_CUST_RESERV_3,   
         
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_GAIN_R,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_GAIN_G,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_GAIN_B,
                                                     
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_OFFSET_R,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_OFFSET_G,
    GLUELAYER_CMD_M_EEP_OFFSET_FAC_CLR_OFFSET_B,
                                                   
    /* All Other Settings starts here. */            
    GLUELAYER_CMD_M_EEP_OFFSET_ACFG_MISC,                                                            
    GLUELAYER_CMD_M_ACFG_FILESYS_CLR_INPUT_SRC_NUM ,                                             
    GLUELAYER_CMD_M_ACFG_ODM_CLR_GAIN_OFFSET_MIN,
    GLUELAYER_CMD_M_ACFG_ODM_CLR_GAIN_OFFSET_MAX,                                                   
    
    GLUELAYER_CMD_M_DRV_CUSTOM_CUST_SPEC_TYPE_VIZIO_LED_LOGO_CTRL,
    GLUELAYER_CMD_M_DRV_CUSTOM_CUST_SPEC_TYPE_INFO_BURNIN_MODE,
                                                                 
    GLUELAYER_CMD_M_EQ_DRV_MIN,
    GLUELAYER_CMD_M_EQ_DRV_MAX,      
    
    GLUELAYER_CMD_M_AUDIO_OUTPUT_TYPE_LINE_OUT ,
    GLUELAYER_CMD_M_AUDIO_OUTPUT_TYPE_HEADPHONE,
    GLUELAYER_CMD_M_AUDIO_OUTPUT_TYPE_BOTH,
    GLUELAYER_CMD_M_AUDIO_OUTPUT_TYPE_END ,
    GLUELAYER_CMD_M_PLF_OPT_MODEL_NAME_LEN ,
    
    GLUELAYER_CMD_M_NAV_COMP_ID_FAC_MSG,
    GLUELAYER_CMD_M_COMP_EXC_SET_CPL_FAC_CHECK,
        
/* MLM IDX */
    GLUELAYER_CMD_M_MLM_ISL_NUM_KEY,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_TV,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_TV_DTV,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_TV_ATV,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_COMBI,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_COMBI_0,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_COMBI_1,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_COMBI_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_COMBI_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_CVBS ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_CVBS_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_CVBS_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_CVBS_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_CVBS_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_S_VIDEO ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_S_VIDEO_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_S_VIDEO_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_S_VIDEO_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_S_VIDEO_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_YPBPR ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_YPBPR_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_YPBPR_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_YPBPR_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_YPBPR_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_SCART ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_SCART_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_SCART_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_SCART_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_SCART_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_HDMI ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_HDMI_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_HDMI_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_HDMI_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_HDMI_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_DVI ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_DVI_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_DVI_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_DVI_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_DVI_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_VGA ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_VGA_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_VGA_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_VGA_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_VGA_3 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_DVD_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_AUDIO_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_MMP ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_MMP_0 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_MMP_1 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_MMP_2 ,
    GLUELAYER_CMD_M_MLM_ISL_KEY_MSG_UNKNOWN ,
    
    GLUELAYER_CMD_M_END,
    GLUELAYER_CMD_M_MAX = 0x00FFFFFF
}E_GLUELAYER_CMD_MACRO;


/* GLUELAYER_CMD_GRP_API */
typedef enum {
    /* CTRL MACRO */
    GLUELAYER_CMD_A_APP_CFG_FAC_CLR_TEMP = 1,
    GLUELAYER_CMD_A_APP_CUST_FAC,
    GLUELAYER_CMD_A_APP_CUST_PLT_OPT,
    GLUELAYER_CMD_A_APP_CFG_UPDATE_GAMMA_IN_PIC_MODE ,
    GLUELAYER_CMD_A_APP_CFG_CUSTOM_PQ_DEF_TBL,
    GLUELAYER_CMD_A_APP_CFG_CUSTOM_PRO_PQ_DEF_TBL,
    GLUELAYER_CMD_A_APP_CUST_RESET_DAYLIGHT_SAVING_SETTING_IN_TV_RESET ,                                                                          
    GLUELAYER_CMD_A_APP_CLR_TEMP_CUSTOME_4_RETAIL_MODE ,
    GLUELAYER_CMD_A_APP_CUST_REDUCE_BLUR_SUPPORT,
    GLUELAYER_CMD_A_APP_CFG_STORE_DEMO_LED,
    GLUELAYER_CMD_A_APP_CUST_SPEC_TYPE,
    GLUELAYER_CMD_A_APP_MENU_CUSTOM_DRC_LIGHTSENSOR,
    GLUELAYER_CMD_A_APP_NAV_CUSTOM_RCU_KEY_PRE_HANDLER,
    GLUELAYER_CMD_A_NAV_CUSTOM_RCU_KEY_PRE_HANDLER,
    GLUELAYER_CMD_A_NAV_CUSTOM_SYSTEM_KEY_CB,
    
    GLUELAYER_CMD_A_FACTORY_SET_REGISTRATION,
    GLUELAYER_CMD_A_FACT_PARSER_INIT,
    GLUELAYER_CMD_A_NAV_FAC_REGISTER,
    GLUELAYER_CMD_A_BURNING_MODE_REGISTER,
    GLUELAYER_CMD_A_A_NAV_FLICKER_TOGGLE_PATTERN,
    GLUELAYER_CMD_A_A_NAV_FLICKER_REGISTER,
    GLUELAYER_CMD_A_CFG_CUST_FAC_CLEAR_CH_TABLE,
    GLUELAYER_CMD_A_ACFG_CUST_FACTORY_PRE_INIT,
    GLUELAYER_CMD_A_ACFG_CUST_FACTORY_POST_INIT,
    GLUELAYER_CMD_A_ACFG_CUST_FACT_GET_MIN_MAX,
    GLUELAYER_CMD_A_ACFG_CUST_FACT_INCR,
    GLUELAYER_CMD_A_ACFG_CUST_FACT_DECR,
    GLUELAYER_CMD_A_ACFG_CUST_FACT_GET,
    GLUELAYER_CMD_A_ACFG_CUST_FACT_SET,
    GLUELAYER_CMD_A_ACFG_CUST_FACT_UPDATE,
    GLUELAYER_CMD_A_CFG_CUSTOM_RESET_FAC,
    GLUELAYER_CMD_A_CFG_CUSTOM_RESET_DAYLIGHT_SAVING_SETTING,
    GLUELAYER_CMD_A_CFG_CUSTOM_RESET_FAC_CLR_TMP,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_FAC_RESERV,
    GLUELAYER_CMD_A_CFG_CUSTOM_SET_FAC_RESERV,
    GLUELAYER_CMD_A_CFG_CUSTOM_SET_FACTORY_COLORTEMP,
    GLUELAYER_CMD_A_CFG_CUSTOM_RESET_FACTORY_COLORTEMP,
    GLUELAYER_CMD_A_CFG_CUST_FAC_DISCRETE_KEY_HANDLER_FCT,
    GLUELAYER_CMD_A_CFG_CUSTOM_SET_LIGHT_SENSOR_GAMMA_INDEX,
    GLUELAYER_CMD_A_CFG_CUSTOM_CHECK_XVYCC,
    GLUELAYER_CMD_A_CFG_RESET_CLR_TMP_DEFAULT,   
    GLUELAYER_CMD_A_ACFG_CUST_ODM_VIDEO_UPDATE,
    GLUELAYER_CMD_A_ACFG_CUST_ODM_AUDIO_UPDATE,
    GLUELAYER_CMD_A_ACFG_CUST_ODM_VGA_UPDATE,
    GLUELAYER_CMD_A_ACFG_CUST_ODM_OVERWRITE_3D_PQ_DEFAULT,
    GLUELAYER_CMD_A_ACFG_CUST_ODM_OVERWRITE_PQ_DEFAULT,
    GLUELAYER_CMD_A_CFG_CUSTOM_ODM_IS_EMANUAL_SUPPORT,
    GLUELAYER_CMD_A_ACFG_CUSTOM_ODM_UPDATE_SMART_DIMMING,
    GLUELAYER_CMD_A_CFG_CUSTOM_ODM_IS_LIGHTSENSOR_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_ODM_IS_DCR_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_SET_AUD_SRS_BYPASS,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_AUD_SRS_BYPASS,
    GLUELAYER_CMD_A_CFG_CUSTOM_COPY2ALL_USR_CLR_TEMP,
    GLUELAYER_CMD_A_CFG_CUSTOM_BACKUP_USR_CLR_TEMP,
    GLUELAYER_CMD_A_CFG_CUSTOM_RECALL_USR_CLR_TEMP,   
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_SRCID_COM_OR_AV,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_SPDIF_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_WIFI_REMOTE_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_WFD_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_RGB_ON_OFF,
    GLUELAYER_CMD_A_CFG_CUSTOM_SET_RGB_ON_OFF,
    GLUELAYER_CMD_A_CFG_CUSTOM_SET_PQ_EXP_COLOR,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_PQ_EXP_COLOR,
    GLUELAYER_CMD_A_ACFG_CUST_ODM_OVERWRITE_AQ_DEFAULT,
    GLUELAYER_CMD_A_ACFG_CUSTOM_ODM_UPDATE_ALL,
    GLUELAYER_CMD_A_ACFG_CUSTOM_ODM_PRE_UPDATE_ALL,

    GLUELAYER_CMD_A_CFG_CUSTOM_GET_OPTICAL_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_LCDIM_USED,
    GLUELAYER_CMD_A_CFG_ODM_UPDATE_REDUCE_BLUR,
    GLUELAYER_CMD_A_CFG_ODM_SET_REDUCE_BLUR,
    GLUELAYER_CMD_A_ACFG_CUST_PLF_OPT_PRE_INIT,
    GLUELAYER_CMD_A_ACFG_CUST_PLF_OPT_POST_INIT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_3D_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_PIP_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_BT_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_3D_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_PIP_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_BT_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_MODEL_NAME,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_PQ_VERSION,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_LIGHTSENSOR,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_LETTERBOX_DETECTION,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_DCR_SETTING,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_LIGHTSENSOR,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_DCR_SETTING,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_MODEL_MEMC_FLAG,
    GLUELAYER_CMD_A_CFG_CUSTOM_GET_IS_SUPPORT_LOCAL_DIMMING,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_IS_ANALOG_AUD_OUT_SUPPORT,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_SET_CC_ONOFF,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_USB_NUM,
    GLUELAYER_CMD_A_GET_YPBPR_FLAG,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_MODEL_ID,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_START_AGING,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_END_AGING,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_AQ_VERSION,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_GET_DEVICE_CLASS,
    GLUELAYER_CMD_A_CFG_CUSTOM_PLF_OPT_MODEL_NAME_WITH_LD,
    
    GLUELAYER_CMD_A_ACFG_PRE_CH_CLI_IMPORT_REC_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_CLI_ADD_AIR_ANA_REC_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_CLI_ADD_AIR_DIG_REC_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_CLI_ADD_CAB_DIG_REC_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_CLI_ADD_CAB_ANA_REC_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_DUMP_CHANNEL_INFO_2_USB_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_DUMP_CHANNEL_INFO_2_TERM_FAC,
    GLUELAYER_CMD_A_ACFG_PRE_CH_LOAD_PRESET_CHANNEL_FAC,
    GLUELAYER_CMD_A_ACFG_SAC_LOAD_DEFAULT_CHANNEL_FAC,
    GLUELAYER_CMD_A_ACFG_SAC_DUMP_CHANNEL_INFO_FAC,
    GLUELAYER_CMD_A_ACFG_SAC_GET_CHANNEL_FREQENCY_FAC,
    
#ifdef APP_EMANUAL_SUPPORT
   GLUELAYER_CMD_A_START_USER_MANUAL_BY_MODEL,
#endif
    
    GLUELAYER_CMD_A_GET_USB_PORT_NUM_BY_MODEL,
    GLUELAYER_CMD_A_IS_DLNA_ENABLE,
    
#ifdef APP_RETAIL_MODE_SUPPORT
    GLUELAYER_CMD_A_START_RETAIL_DEMO_BY_MODEL,
#endif

    GLUELAYER_CMD_A_MENU_CUST_GET_VER_KEY_LIST_PATTERN,
    
    GLUELAYER_CMD_A_MENU_CUSTOM_INIT_FACTORY_TREE,
    GLUELAYER_CMD_A_MENU_CUSTOM_VERSION_KEY_FILTER,
    GLUELAYER_CMD_A_MENU_CUST_FAC_INIT,
    GLUELAYER_CMD_A_MENU_CUST_FAC_SETTINGS_INIT,
    GLUELAYER_CMD_A_MENU_CUST_FACT_EXIT,
    GLUELAYER_CMD_A_MENU_CUST_FACT_IS_RESET_PAGE,

    GLUELAYER_CMD_A_SET_FAC_POWER_STATUS,
    GLUELAYER_CMD_A_GET_FAC_POWER_STATUS,
    GLUELAYER_CMD_A_SET_FAC_SITE_AIR,
    GLUELAYER_CMD_A_SET_FAC_SITE_CABLE,
    GLUELAYER_CMD_A_GET_FAC_SITE_AIR,
    GLUELAYER_CMD_A_GET_FAC_SITE_CABLE,
    GLUELAYER_CMD_A_SET_FAC_INTERNAL_PATTERN,
    GLUELAYER_CMD_A_SET_FAC_SRS_SETTING,
    GLUELAYER_CMD_A_GET_FAC_SRS_SETTING,

    GLUELAYER_CMD_A__SET_FAC_CLR_PATTERN_SETTING,
    GLUELAYER_CMD_A__GET_FAC_CLR_PATTERN_SETTING,
    GLUELAYER_CMD_A_MENU_FAC_PAGE_MESSAGE_BOX_INIT,
    GLUELAYER_CMD_A_MENU_FAC_PAGE_LIGHT_SENSOR_INIT,
    GLUELAYER_CMD_A_SET_FAC_MODEL_INDEX_SETTING,
    GLUELAYER_CMD_A_GET_FAC_MODEL_INDEX_SETTING,
    GLUELAYER_CMD_A_MENU_FAC_AGING_INIT,
    
    GLUELAYER_CMD_A_NAV_CUSTOM_REGISTER_COMPONENTS_ODM,
    
    GLUELAYER_CMD_A_MLM_ISL_GET_TEXT,
    GLUELAYER_CMD_A_MLM_ISL_S639_TO_LANGIDX,
    GLUELAYER_CMD_A_MLM_ISL_LANGIDX_TO_S639,
    GLUELAYER_CMD_A_ISL_GET_ALIKE_ID,
    GLUELAYER_CMD_A_A_ISL_GET_DISPLAY_NAME,
    GLUELAYER_CMD_A_A_ISL_GET_DISPLAY_NAME_EX,

    GLUELAYER_CMD_A_WZD_IMAGE_CUST_CREATE,
    GLUELAYER_CMD_A_WZD_IMAGE_CUST_INIT,

    GLUELAYER_CMD_A_FAC_NEED_BURNING_IN,
    GLUELAYER_CMD_A_FAC_DISABLE_RTC_WAKEUP,
    GLUELAYER_CMD_A_FAC_DYNAMIC_RGB_RANGE,

    GLUELAYER_CMD_A_HDR_PANEL_NITS,

    GLUELAYER_CMD_A_END,
    GLUELAYER_CMD_A_MAX = 0x00FFFFFF
} E_GLUELAYER_CMD_API;

typedef enum
{
    GLUELAYER_CMD_S_M_AUI4_FAC_TRIGGER_KEY = 1,
    GLUELAYER_CMD_S_PQ_DFT_TBL,
    GLUELAYER_CMD_S_PRO_PQ_DFT_TBL,
    GLUELAYER_CMD_S_HDR_HLG_PQ_DFT_TBL,
    GLUELAYER_CMD_S_DOBLY_VERSION_PQ_DFT_TBL,
    GLUELAYER_CMD_S_HLG_PQ_DFT_TBL,
    GLUELAYER_CMD_S_END,
    GLUELAYER_CMD_S_MAX = 0x00FFFFFF
} E_GLUELAYER_CMD_STRUCT;

#endif  //_GLUE_LAYER_COMM_H_
