/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.
 * All rights reserved.
 * 
 * Unauthorized use, practice, perform, copy, distribution, reproduction,
 * or disclosure of this information in whole or in part is prohibited.
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: #21 $
 * $Date:   
 * $Author: 
 * $CCRevision: $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/
#ifndef _TPV_fac_mlm_h_
#define _TPV_fac_mlm_h_

/*-----------------------------------------------------------------------------
                   include files
-----------------------------------------------------------------------------*/
#include "u_common.h"

/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
-----------------------------------------------------------------------------*/
#define MLM_FAC_TEXT(lang, key) (((lang) < MLM_FAC_NUM_LANG && (key) < MLM_FAC_NUM_KEY) ? _aaw2s_mlm_fac_msg_tbl[key][lang] : NULL)

#define MLM_FAC_NUM_LANG 3
#define MLM_FAC_NUM_KEY 187

#define MLM_FAC_KEY_MSG_BRAND 0
#define MLM_FAC_KEY_MSG_MAIN_MCU_VER 1
#define MLM_FAC_KEY_MSG_BOOT_LOADER_VER 2
#define MLM_FAC_KEY_MSG_EEPROM_VER 3
#define MLM_FAC_KEY_MSG_SUB_MCU_VER 4
#define MLM_FAC_KEY_MSG_DATE 5
#define MLM_FAC_KEY_MSG_MODEL_NAME 6
#define MLM_FAC_KEY_MSG_SCALER 7
#define MLM_FAC_KEY_MSG_TUNER_TYPE 8
#define MLM_FAC_KEY_MSG_PANEL_TYPE 9
#define MLM_FAC_KEY_MSG_CURRENT_SOURCE 10
#define MLM_FAC_KEY_MSG_AUTO_COLOR 11
#define MLM_FAC_KEY_MSG_ADC_R_GAIN 12
#define MLM_FAC_KEY_MSG_ADC_G_GAIN 13
#define MLM_FAC_KEY_MSG_ADC_B_GAIN 14
#define MLM_FAC_KEY_MSG_ADC_R_OFFSET 15
#define MLM_FAC_KEY_MSG_ADC_G_OFFSET 16
#define MLM_FAC_KEY_MSG_ADC_B_OFFSET 17
#define MLM_FAC_KEY_MSG_COLOR_TEMP 18
#define MLM_FAC_KEY_MSG_SCALER_R_GAIN 19
#define MLM_FAC_KEY_MSG_SCALER_G_GAIN 20
#define MLM_FAC_KEY_MSG_SCALER_B_GAIN 21
#define MLM_FAC_KEY_MSG_SCALER_R_OFFSET 22
#define MLM_FAC_KEY_MSG_SCALER_G_OFFSET 23
#define MLM_FAC_KEY_MSG_SCALER_B_OFFSET 24
#define MLM_FAC_KEY_MSG_CLR_COPY 25
#define MLM_FAC_KEY_MSG_BURN_IN 26
#define MLM_FAC_KEY_MSG_EEPROM_INIT 27
#define MLM_FAC_KEY_MSG_HDMI_EDID_LOAD 28
#define MLM_FAC_KEY_MSG_BACK_LIT_TIME 29
#define MLM_FAC_KEY_MSG_BACKLIGHT_MAX 30
#define MLM_FAC_KEY_MSG_BACKLIGHT_MIN 31
#define MLM_FAC_KEY_MSG_LANGUAGE 32
#define MLM_FAC_KEY_MSG_RESET 33
#define MLM_FAC_KEY_MSG_VGA_SWITCH 34
#define MLM_FAC_KEY_MSG_VCOM 35
#define MLM_FAC_KEY_MSG_WB_PAT 36
#define MLM_FAC_KEY_MSG_EXIT 37
#define MLM_FAC_KEY_MSG_YES 38
#define MLM_FAC_KEY_MSG_NO 39
#define MLM_FAC_KEY_MSG_RETURN 40
#define MLM_FAC_KEY_MSG_BRAND_NAME 41
#define MLM_FAC_KEY_MSG_SCALER_NAME 42
#define MLM_FAC_KEY_MSG_DONE 43
#define MLM_FAC_KEY_MSG_FAIL 44
#define MLM_FAC_KEY_MSG_WARM 45
#define MLM_FAC_KEY_MSG_COOL 46
#define MLM_FAC_KEY_MSG_NORMAL 47
#define MLM_FAC_KEY_MSG_USER 48
#define MLM_FAC_KEY_MSG_PRESS 49
#define MLM_FAC_KEY_MSG_ENTER_FAC 50
#define MLM_FAC_KEY_MSG_LEAVE_FAC 51
#define MLM_FAC_KEY_MSG_TEST_MODE_ON 52
#define MLM_FAC_KEY_MSG_VIRGIN_MODE 53
#define MLM_FAC_KEY_MSG_VIRGIN_MODE_OFF 54
#define MLM_FAC_KEY_MSG_ORT_MODE_ON 55
#define MLM_FAC_KEY_MSG_ORT_MODE_OFF 56
#define MLM_FAC_KEY_MSG_AV_RESET 57
#define MLM_FAC_KEY_MSG_BRIGHT_50P 58
#define MLM_FAC_KEY_MSG_BRIGHT_100P 59
#define MLM_FAC_KEY_MSG_CONTRAST_50P 60
#define MLM_FAC_KEY_MSG_CONTRAST_100P 61
#define MLM_FAC_KEY_MSG_PIC_MODE_USER 62
#define MLM_FAC_KEY_MSG_PIC_MODE_DYNAMIC 63
#define MLM_FAC_KEY_MSG_PIC_MODE_STANDARD 64
#define MLM_FAC_KEY_MSG_PIC_MODE_MILD 65
#define MLM_FAC_KEY_MSG_PIC_MODE_MOVIE 66
#define MLM_FAC_KEY_MSG_PIC_MODE_ECO 67
#define MLM_FAC_KEY_MSG_WB_NORMAL 68
#define MLM_FAC_KEY_MSG_WB_WARM 69
#define MLM_FAC_KEY_MSG_WB_COOL 70
#define MLM_FAC_KEY_MSG_WB_USER 71
#define MLM_FAC_KEY_MSG_SOUND_MODE_STEREO 72
#define MLM_FAC_KEY_MSG_AVL_OFF 73
#define MLM_FAC_KEY_MSG_BALANCE_RIGHT 74
#define MLM_FAC_KEY_MSG_BALANCE_LEFT 75
#define MLM_FAC_KEY_MSG_VOLUME_100P 76
#define MLM_FAC_KEY_MSG_VOLUME_75P 77
#define MLM_FAC_KEY_MSG_VOLUME_50P 78
#define MLM_FAC_KEY_MSG_VOLUME_25P 79
#define MLM_FAC_KEY_MSG_AUTO_COLOR_PROCESS 80
#define MLM_FAC_KEY_MSG_AUTO_COLOR_DONE 81
#define MLM_FAC_KEY_MSG_AUTO_COLOR_FAIL 82
#define MLM_FAC_KEY_MSG_SET_ALL_PM 83
#define MLM_FAC_KEY_MSG_SET_TO_FM 84
#define MLM_FAC_KEY_MSG_EDID 85
#define MLM_FAC_KEY_MSG_UART 86
#define MLM_FAC_KEY_MSG_EDID_WP_EN 87
#define MLM_FAC_KEY_MSG_EDID_WP_DIS 88
#define MLM_FAC_KEY_MSG_URC_VGA_SWITCH 89
#define MLM_FAC_KEY_MSG_TEST_MODE 90
#define MLM_FAC_KEY_MSG_BACKLIGHT_50 91
#define MLM_FAC_KEY_MSG_BACKLIGHT_100 92
#define MLM_FAC_KEY_MSG_PRESET_CH 93
#define MLM_FAC_KEY_MSG_BURN_IN_ON 94
#define MLM_FAC_KEY_MSG_BURN_IN_OFF 95
#define MLM_FAC_KEY_MSG_RESET_FINISH 96
#define MLM_FAC_KEY_MSG_SURROUND_ON 97
#define MLM_FAC_KEY_MSG_SURROUND_OFF 98
#define MLM_FAC_KEY_MSG_DCR_ON 99
#define MLM_FAC_KEY_MSG_DCR_OFF 100
#define MLM_FAC_KEY_MSG_VOL_MAX 101
#define MLM_FAC_KEY_MSG_VOL_BUZZ 102
#define MLM_FAC_KEY_MSG_PATTERN_RED 103
#define MLM_FAC_KEY_MSG_PATTERN_GREEN 104
#define MLM_FAC_KEY_MSG_PATTERN_BLUE 105
#define MLM_FAC_KEY_MSG_PATTERN_WHITE 106
#define MLM_FAC_KEY_MSG_PATTERN_BLACK 107
#define MLM_FAC_KEY_MSG_PATTERN_OFF 108
#define MLM_FAC_KEY_MSG_AUTO_CONFIG 109
#define MLM_FAC_KEY_MSG_BLK_50P 110
#define MLM_FAC_KEY_MSG_BLK_100P 111
#define MLM_FAC_KEY_MSG_VCOM_VALUE 112
#define MLM_FAC_KEY_MSG_VCOM_STORE 113
#define MLM_FAC_KEY_MSG_GAMMA1 114
#define MLM_FAC_KEY_MSG_GAMMA2 115
#define MLM_FAC_KEY_MSG_GAMMA3 116
#define MLM_FAC_KEY_MSG_GAMMA4 117
#define MLM_FAC_KEY_MSG_GAMMA5 118
#define MLM_FAC_KEY_MSG_GAMMA6 119
#define MLM_FAC_KEY_MSG_GAMMA7 120
#define MLM_FAC_KEY_MSG_GAMMA8 121
#define MLM_FAC_KEY_MSG_TCON_EXIT 122
#define MLM_FAC_KEY_MSG_ANTENNA 123
#define MLM_FAC_KEY_MSG_CABLE 124
#define MLM_FAC_KEY_MSG_LED_OFF 125
#define MLM_FAC_KEY_MSG_LED_ON 126
#define MLM_FAC_KEY_MSG_PIC_MODE_HOME 127
#define MLM_FAC_KEY_MSG_PIC_MODE_GAME 128
#define MLM_FAC_KEY_MSG_PIC_MODE_RETAIL 129
#define MLM_FAC_KEY_MSG_PIC_MODE_PHOTO 130
#define MLM_FAC_KEY_MSG_PIC_MODE_CUSTOM 131
#define MLM_FAC_KEY_MSG_OAD_ENABLE 132
#define MLM_FAC_KEY_MSG_DUMP_CH_INFO 133
#define MLM_FAC_KEY_MSG_FLIP 134
#define MLM_FAC_KEY_MSG_MIRROR 135
#define MLM_FAC_KEY_MSG_EEPROM_DUMP 136
#define MLM_FAC_KEY_MSG_AUD_SRS_BYPASS 137
#define MLM_FAC_KEY_MSG_PIC_STANDARD 138
#define MLM_FAC_KEY_MSG_PIC_MOVIE 139
#define MLM_FAC_KEY_MSG_PIC_GAME 140
#define MLM_FAC_KEY_MSG_PIC_VIVID 141
#define MLM_FAC_KEY_MSG_PIC_FOOTBALL 142
#define MLM_FAC_KEY_MSG_PIC_GOLF 143
#define MLM_FAC_KEY_MSG_PIC_BASKETBALL 144
#define MLM_FAC_KEY_MSG_PIC_BASEBALL 145
#define MLM_FAC_KEY_MSG_PIC_CUSTOM 146
#define MLM_FAC_KEY_MSG_NO_USB 147
#define MLM_FAC_KEY_MSG_HDMI_PORT_NUM 148
#define MLM_FAC_KEY_MSG_INSTALL_ULPK 149
#define MLM_FAC_KEY_MSG_QUERY_ULPK 150
#define MLM_FAC_KEY_MSG_ERASE_ULPK 151
#define MLM_FAC_KEY_MSG_ARC_OFF 152
#define MLM_FAC_KEY_MSG_ARC_ON 153
#define MLM_FAC_KEY_MSG_LSR_OFF 154
#define MLM_FAC_KEY_MSG_LSR_ON 155
#define MLM_FAC_KEY_MSG_3D2D_3D 156
#define MLM_FAC_KEY_MSG_3D2D_2D 157
#define MLM_FAC_KEY_MSG_NOT_SUPPORT 158
#define MLM_FAC_KEY_MSG_ITEM_VIVID 159
#define MLM_FAC_KEY_MSG_ITEM_BRIGHT 160
#define MLM_FAC_KEY_MSG_ITEM_CALIBRATED 161
#define MLM_FAC_KEY_MSG_ITEM_CALIBRATED_DARK 162
#define MLM_FAC_KEY_MSG_ITEM_GAME 163
#define MLM_FAC_KEY_MSG_ITEM_SPORT 164
#define MLM_FAC_KEY_MSG_PQ_VER 165
#define MLM_FAC_KEY_MSG_AQ_VER 166
#define MLM_FAC_KEY_MSG_WINDOW_PATTERN 167
#define MLM_FAC_KEY_MSG_ON 168
#define MLM_FAC_KEY_MSG_OFF 169
#define MLM_FAC_KEY_MSG_RJ45_MAC 170
#define MLM_FAC_KEY_MSG_WIFI_MAC 171
#define MLM_FAC_KEY_MSG_BT_MAC 172
#define MLM_FAC_KEY_MSG_SN 173
#define MLM_FAC_KEY_MSG_ULPK_ID 174
#define MLM_FAC_KEY_MSG_BLE_SIGNAL_METER 175
#define MLM_FAC_KEY_MSG_COLOR_TUNER 176
#define MLM_FAC_KEY_MSG_BACKLIGHT_CHECK 177
#define MLM_FAC_KEY_MSG_FACTORY_GAMMA_DATA 178
#define MLM_FAC_KEY_MSG_PQ_BYPASS 179
#define MLM_FAC_KEY_MSG_PANEL_NITS 180
#define MLM_FAC_KEY_MSG_HDCP_CHECK 181
#define MLM_FAC_KEY_MSG_OLED_SETTING 182
#define MLM_FAC_KEY_MSG_EARC_MUTE 183
#define MLM_FAC_KEY_MSG_EARC_WORD_LENGTH 184
#define MLM_FAC_KEY_MSG_EARC_LAYOUT 185
#define MLM_FAC_KEY_MSG_CPU_TEMPERATURE 186

#define MLM_FAC_LANG_ENG 0
#define MLM_FAC_LANG_FRE 1
#define MLM_FAC_LANG_SPA 2

/*-----------------------------------------------------------------------------
                    data declarations
-----------------------------------------------------------------------------*/
extern UTF16_T* _aaw2s_mlm_fac_msg_tbl[187][3];

/*-----------------------------------------------------------------------------
                    function declarations
-----------------------------------------------------------------------------*/
extern UINT16 mlm_fac_s639_to_langidx(ISO_639_LANG_T s639_lang);
extern VOID mlm_fac_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang);

#endif /* _TPV_fac_mlm_h_ */
