/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.
 * All rights reserved.
 * 
 * Unauthorized use, practice, perform, copy, distribution, reproduction,
 * or disclosure of this information in whole or in part is prohibited.
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: #21 $
 * $Date:   
 * $Author: 
 * $CCRevision: $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/
#ifndef _stimer_mlm_h_
#define _stimer_mlm_h_

/*-----------------------------------------------------------------------------
                   include files
-----------------------------------------------------------------------------*/
#include "u_common.h"

/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
-----------------------------------------------------------------------------*/
#define MLM_STIMER_TEXT(lang, key) mlm_stimer_get_text(lang, key)

#define MLM_STIMER_NUM_LANG 3
#define MLM_STIMER_NUM_KEY 3

#define MLM_STIMER_KEY_MSG_OFF 0
#define MLM_STIMER_KEY_MSG_MIN1 1
#define MLM_STIMER_KEY_MSG_MIN2 2

#define MLM_STIMER_LANG_ENG 0
#define MLM_STIMER_LANG_FRE 1
#define MLM_STIMER_LANG_SPA 2

/*-----------------------------------------------------------------------------
                    data declarations
-----------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                    function declarations
-----------------------------------------------------------------------------*/
extern UTF16_T* mlm_stimer_get_text(UINT16 ui2_lang, UINT16 ui2_key);
extern UINT16 mlm_stimer_s639_to_langidx(ISO_639_LANG_T s639_lang);
extern VOID mlm_stimer_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang);

#endif /* _stimer_mlm_h_ */
