/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.                           
 * All rights reserved.                                                        
 *                                                                             
 * Unauthorized use, practice, perform, copy, distribution, reproduction,      
 * or disclosure of this information in whole or in part is prohibited.        
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: 
 * $Date: 
 * $Author: 
 * $CCRevision: stimer_mlm.c,v $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:                                                                
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                   include files                                               
-----------------------------------------------------------------------------*/
#include "u_common.h"
#include "u_sys_name.h"
#include "c_cl.h"
#include "c_os.h"
#include "amb/a_amb.h"

#ifdef APP_MLMGEN_CUSTOM_LOGIC
#include "res/app_util/mlmgen/a_mlmgen.h"
#endif

/*-----------------------------------------------------------------------------
                    data declarations                                          
-----------------------------------------------------------------------------*/
typedef struct _MLM_STIMER_TEXT_T
{
    UTF16_T     w2s_msg_off[8];
    UTF16_T     w2s_msg_min1[8];
    UTF16_T     w2s_msg_min2[9];
} MLM_STIMER_TEXT_T;

static UINT16 ui1_g_mlm_cur_lang_idx = 0xFFFF;
static MLM_STIMER_TEXT_T t_g_mlm_text;

static UINT8   at_g_compressed_eng[] =
{
    0xf3, 0x67, 0x48, 0x03, 0x42, 0x04, 0x50, 0x60, 0xc8, 0x65,
    0xc8, 0x64, 0xc8, 0x63, 0x28, 0x65, 0x28, 0x61, 0x48, 0xc5,
    0xe0, 0x17, 0x03, 0x45, 0x00, 0x00
};

static UINT8   at_g_compressed_fre[] =
{
    0x73, 0x64, 0x28, 0x02, 0xc2, 0x57, 0x0c, 0x25, 0x0c, 0x2f,
    0x19, 0x40, 0x40, 0x81, 0x21, 0x97, 0x21, 0x93, 0x21, 0x8f,
    0xa1, 0x14, 0x28, 0x92, 0x8a, 0xc1, 0x2f, 0x06, 0x8a, 0x00,
    0x00, 0x00
};

static UINT8   at_g_compressed_spa[] =
{
    0x73, 0x64, 0x28, 0x60, 0x48, 0x64, 0x48, 0x07, 0xe2, 0x14,
    0x86, 0x7c, 0x06, 0x06, 0x06, 0x05, 0x86, 0x5c, 0x86, 0x4c,
    0x86, 0x3c, 0x86, 0x52, 0x86, 0x12, 0x2c, 0xfc, 0x62, 0xa0,
    0x08, 0x00, 0x00
};

static UTF16_T*    aw2s_g_txt_tbl[3] =
{
    t_g_mlm_text.w2s_msg_off,
    t_g_mlm_text.w2s_msg_min1,
    t_g_mlm_text.w2s_msg_min2
};

static UINT8* apui1_g_data_tbl[3] =
{
    at_g_compressed_eng,
    at_g_compressed_fre,
    at_g_compressed_spa
};

static SIZE_T az_g_data_len_tbl[3] =
{
    sizeof(at_g_compressed_eng),
    sizeof(at_g_compressed_fre),
    sizeof(at_g_compressed_spa)
};

static HANDLE_T h_g_lock = NULL_HANDLE;

/*-----------------------------------------------------------------------------
                    function declarations                                          
-----------------------------------------------------------------------------*/
static VOID _mlm_stimer_decompress(UINT16 ui2_lang)
{
    INT32       i4_ret;
    HANDLE_T    h_zip_eng = NULL_HANDLE;
    SIZE_T      z_dest_len = sizeof(MLM_STIMER_TEXT_T);

    if(ui2_lang >= 3)    /* MLM_STIMER_LANG_NUM = 3 */
    {
        return;
    }

    do
    {
        i4_ret = c_cl_open_eng(SN_CL_ZIP, NULL, NULL, &h_zip_eng);
        if(i4_ret < 0)
        {
            break;
        }

        i4_ret = c_cl_decompress(h_zip_eng,
                                 apui1_g_data_tbl[ui2_lang],
                                 az_g_data_len_tbl[ui2_lang],
                                 0,
                                 CL_NULL_PARAM_TYPE,
                                 NULL,
                                 &t_g_mlm_text,
                                 &z_dest_len,
                                 NULL);
        if(i4_ret < 0)
        {
            break;
        }

    }while(0);

    if(i4_ret < 0)
    {
        c_memset(&t_g_mlm_text, 0, sizeof(MLM_STIMER_TEXT_T));
    }

    if(h_zip_eng != (HANDLE_T)NULL)
    {
        c_cl_close(h_zip_eng);
    }
}

static VOID _mlm_stimer_lock(VOID)
{

    /* Acquire lock */
    if(h_g_lock == NULL_HANDLE)
    {
        a_amb_lock();
        if(h_g_lock == NULL_HANDLE)
        {
            c_sema_create(&h_g_lock,
                          X_SEMA_TYPE_MUTEX,
                          X_SEMA_STATE_UNLOCK);
        }
        a_amb_unlock();
    }

    /* Lock */
    if(h_g_lock)
    {
        c_sema_lock(h_g_lock, X_SEMA_OPTION_WAIT);
    }
}

static VOID _mlm_stimer_unlock(VOID)
{
    /* Unlock */
    if(h_g_lock)
    {
        c_sema_unlock(h_g_lock);
    }
}

UTF16_T* mlm_stimer_get_text(UINT16 ui2_lang, UINT16 ui2_key)
{
    if(ui2_lang != ui1_g_mlm_cur_lang_idx)
    {
        _mlm_stimer_lock();
        if(ui2_lang != ui1_g_mlm_cur_lang_idx)
        {
            _mlm_stimer_decompress(ui2_lang);
            ui1_g_mlm_cur_lang_idx = ui2_lang;
        }
        _mlm_stimer_unlock();
    }

#ifdef APP_MLM_CENTER_SUPPORT /* ExcelGen mechanism. */ 
    if (   (aw2s_g_txt_tbl[ui2_key][0] != 0 && aw2s_g_txt_tbl[ui2_key][0] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][1] != 0 && aw2s_g_txt_tbl[ui2_key][1] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][2] != 0 && aw2s_g_txt_tbl[ui2_key][2] == (UTF16_T)L'I')  &&
           (aw2s_g_txt_tbl[ui2_key][3] != 0 && aw2s_g_txt_tbl[ui2_key][3] == (UTF16_T)L'D') )
    {
        extern UTF16_T* mlm_center_get_text_by_hint (CHAR* ps_module_name, UINT16 ui2_lang, UTF16_T* pw2s_hint);

        return mlm_center_get_text_by_hint ("STIMER", ui2_lang, aw2s_g_txt_tbl[ui2_key]);
    }
#endif

    return aw2s_g_txt_tbl[ui2_key];
}

UINT16 mlm_stimer_s639_to_langidx(ISO_639_LANG_T s639_lang)
{
    UINT16 ui2_lang_idx = 0; 

    if(s639_lang == NULL)
    {
        ui2_lang_idx = 0;
        return ui2_lang_idx;
    }
    if(c_strncmp(s639_lang,"eng",3) ==0)
    {
        ui2_lang_idx = 0; /*MLM_STIMER_LANG_ENG*/
    }
    else if(c_strncmp(s639_lang,"fre",3) ==0)
    {
        ui2_lang_idx = 1; /*MLM_STIMER_LANG_FRE*/
    }
    else if(c_strncmp(s639_lang,"spa",3) ==0)
    {
        ui2_lang_idx = 2; /*MLM_STIMER_LANG_SPA*/
    }
    else
    {
        ui2_lang_idx = 0; /*MLM_STIMER_LANG_ENG*/
    }
#ifdef MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN
    return MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN("STIMER", s639_lang, ui2_lang_idx);
#else
    return ui2_lang_idx;
#endif
}
VOID mlm_stimer_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang)
{
    if(s639_lang == NULL)
    {
        return;
    }
    switch(ui2_lang)
    {
        case 0: /*MLM_STIMER_LANG_ENG*/
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
        case 1: /*MLM_STIMER_LANG_FRE*/
            c_strncpy(s639_lang,"fre",3);
            s639_lang[3] ='\0';
            break;
        case 2: /*MLM_STIMER_LANG_SPA*/
            c_strncpy(s639_lang,"spa",3);
            s639_lang[3] ='\0';
            break;
        default:
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
    }
}
