/*-----------------------------------------------------------------------------
 * Copyright (c) 2005, CrystalMedia Technology, Inc.                           
 * All rights reserved.                                                        
 *                                                                             
 * Unauthorized use, practice, perform, copy, distribution, reproduction,      
 * or disclosure of this information in whole or in part is prohibited.        
 *-----------------------------------------------------------------------------
 * $RCSfile: mlmgen_renderer.c,v $
 * $Revision: 
 * $Date: 
 * $Author: 
 * $CCRevision: isl_mlm.c,v $
 * $SWAuthor: $
 * $MD5HEX: $
 *
 * Description:                                                                
 *     This file is generated by mlmgen V1.46, which is provided by MediaTek, Inc. 
 *---------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------
                   include files                                               
-----------------------------------------------------------------------------*/
#include "u_common.h"
#include "u_sys_name.h"
#include "c_cl.h"
#include "c_os.h"
#include "amb/a_amb.h"

#ifdef APP_MLMGEN_CUSTOM_LOGIC
#include "res/app_util/mlmgen/a_mlmgen.h"
#endif

/*-----------------------------------------------------------------------------
                    data declarations                                          
-----------------------------------------------------------------------------*/
typedef struct _MLM_ISL_TEXT_T
{
    UTF16_T     w2s_msg_tv[3];
    UTF16_T     w2s_msg_tv_dtv[4];
    UTF16_T     w2s_msg_tv_atv[4];
    UTF16_T     w2s_msg_combi[5];
    UTF16_T     w2s_msg_combi_0[4];
    UTF16_T     w2s_msg_combi_1[4];
    UTF16_T     w2s_msg_combi_2[4];
    UTF16_T     w2s_msg_combi_3[4];
    UTF16_T     w2s_msg_cvbs[10];
    UTF16_T     w2s_msg_cvbs_0[12];
    UTF16_T     w2s_msg_cvbs_1[12];
    UTF16_T     w2s_msg_cvbs_2[12];
    UTF16_T     w2s_msg_cvbs_3[12];
    UTF16_T     w2s_msg_s_video[8];
    UTF16_T     w2s_msg_s_video_0[10];
    UTF16_T     w2s_msg_s_video_1[10];
    UTF16_T     w2s_msg_s_video_2[10];
    UTF16_T     w2s_msg_s_video_3[10];
    UTF16_T     w2s_msg_ypbpr[10];
    UTF16_T     w2s_msg_ypbpr_0[7];
    UTF16_T     w2s_msg_ypbpr_1[11];
    UTF16_T     w2s_msg_ypbpr_2[7];
    UTF16_T     w2s_msg_ypbpr_3[7];
    UTF16_T     w2s_msg_scart[6];
    UTF16_T     w2s_msg_scart_0[8];
    UTF16_T     w2s_msg_scart_1[8];
    UTF16_T     w2s_msg_scart_2[8];
    UTF16_T     w2s_msg_scart_3[8];
    UTF16_T     w2s_msg_hdmi[5];
    UTF16_T     w2s_msg_hdmi_0[7];
    UTF16_T     w2s_msg_hdmi_1[7];
    UTF16_T     w2s_msg_hdmi_2[7];
    UTF16_T     w2s_msg_hdmi_3[7];
    UTF16_T     w2s_msg_dvi[4];
    UTF16_T     w2s_msg_dvi_0[6];
    UTF16_T     w2s_msg_dvi_1[6];
    UTF16_T     w2s_msg_dvi_2[6];
    UTF16_T     w2s_msg_dvi_3[6];
    UTF16_T     w2s_msg_vga[4];
    UTF16_T     w2s_msg_vga_0[6];
    UTF16_T     w2s_msg_vga_1[6];
    UTF16_T     w2s_msg_vga_2[6];
    UTF16_T     w2s_msg_vga_3[6];
    UTF16_T     w2s_msg_dvd_0[4];
    UTF16_T     w2s_msg_audio_0[9];
    UTF16_T     w2s_msg_mmp[4];
    UTF16_T     w2s_msg_mmp_0[7];
    UTF16_T     w2s_msg_mmp_1[6];
    UTF16_T     w2s_msg_mmp_2[6];
    UTF16_T     w2s_msg_unknown[1];
} MLM_ISL_TEXT_T;

static UINT16 ui1_g_mlm_cur_lang_idx = 0xFFFF;
static MLM_ISL_TEXT_T t_g_mlm_text;

static UINT8   at_g_compressed_eng[] =
{
    0x75, 0x52, 0x4b, 0x0e, 0x82, 0x30, 0x10, 0x7d, 0x47, 0xf1,
    0x02, 0xc4, 0xd8, 0x72, 0x01, 0x84, 0x44, 0x59, 0x10, 0x09,
    0x62, 0x2f, 0xa0, 0x26, 0xb2, 0x10, 0x4c, 0x84, 0xfb, 0x3b,
    0x9d, 0xb6, 0x69, 0x8b, 0x65, 0xc3, 0xfb, 0xa4, 0xf3, 0xa7,
    0x87, 0x02, 0x50, 0xa1, 0x67, 0x2c, 0x2c, 0x96, 0xb8, 0xa0,
    0x41, 0xcb, 0x8e, 0xc2, 0xc1, 0xa2, 0xb0, 0x28, 0x2d, 0xe6,
    0xfc, 0x72, 0xc2, 0x1b, 0x1f, 0xfa, 0x7e, 0x31, 0x60, 0xc6,
    0x33, 0xe9, 0xed, 0x38, 0x47, 0xca, 0x17, 0x1b, 0xbe, 0xdc,
    0xf0, 0x75, 0xcd, 0x2b, 0x32, 0xaa, 0x3e, 0xe0, 0x41, 0xce,
    0xf4, 0xa7, 0x4d, 0xad, 0xb5, 0x27, 0x12, 0x9e, 0x4c, 0x78,
    0xf1, 0x4c, 0x23, 0xb9, 0x23, 0x55, 0xf6, 0x5e, 0x16, 0x4d,
    0x92, 0x51, 0xde, 0x3d, 0x3a, 0x9c, 0x70, 0x8c, 0x5c, 0x19,
    0x29, 0xd3, 0x73, 0x49, 0x3b, 0xeb, 0x68, 0xbf, 0x21, 0x77,
    0xbd, 0x7a, 0x2d, 0x56, 0x5a, 0xae, 0xb4, 0xce, 0x75, 0xa6,
    0x7b, 0x35, 0xa8, 0x03, 0x66, 0xba, 0xf2, 0x4a, 0x44, 0x4a,
    0x46, 0x2a, 0xe7, 0x7b, 0x2b, 0x8e, 0x37, 0x68, 0xba, 0x70,
    0x5c, 0x04, 0x5c, 0x06, 0x5c, 0xc7, 0x29, 0x9a, 0xb4, 0x20,
    0x34, 0x13, 0x9b, 0x38, 0xc7, 0x45, 0xc0, 0x65, 0xc0, 0x5d,
    0xbd, 0x8a, 0xff, 0x9a, 0x85, 0x36, 0x3d, 0xf0, 0xa6, 0x6b,
    0xda, 0x2c, 0x70, 0xa3, 0xe9, 0xf4, 0xee, 0x5a, 0xbc, 0xc8,
    0x9d, 0xf9, 0xd6, 0xa0, 0x4e, 0x17, 0xbe, 0xf9, 0x9d, 0x6b,
    0xfa, 0x4b, 0x03, 0x3f, 0x00
};

static UTF16_T*    aw2s_g_txt_tbl[50] =
{
    t_g_mlm_text.w2s_msg_tv,
    t_g_mlm_text.w2s_msg_tv_dtv,
    t_g_mlm_text.w2s_msg_tv_atv,
    t_g_mlm_text.w2s_msg_combi,
    t_g_mlm_text.w2s_msg_combi_0,
    t_g_mlm_text.w2s_msg_combi_1,
    t_g_mlm_text.w2s_msg_combi_2,
    t_g_mlm_text.w2s_msg_combi_3,
    t_g_mlm_text.w2s_msg_cvbs,
    t_g_mlm_text.w2s_msg_cvbs_0,
    t_g_mlm_text.w2s_msg_cvbs_1,
    t_g_mlm_text.w2s_msg_cvbs_2,
    t_g_mlm_text.w2s_msg_cvbs_3,
    t_g_mlm_text.w2s_msg_s_video,
    t_g_mlm_text.w2s_msg_s_video_0,
    t_g_mlm_text.w2s_msg_s_video_1,
    t_g_mlm_text.w2s_msg_s_video_2,
    t_g_mlm_text.w2s_msg_s_video_3,
    t_g_mlm_text.w2s_msg_ypbpr,
    t_g_mlm_text.w2s_msg_ypbpr_0,
    t_g_mlm_text.w2s_msg_ypbpr_1,
    t_g_mlm_text.w2s_msg_ypbpr_2,
    t_g_mlm_text.w2s_msg_ypbpr_3,
    t_g_mlm_text.w2s_msg_scart,
    t_g_mlm_text.w2s_msg_scart_0,
    t_g_mlm_text.w2s_msg_scart_1,
    t_g_mlm_text.w2s_msg_scart_2,
    t_g_mlm_text.w2s_msg_scart_3,
    t_g_mlm_text.w2s_msg_hdmi,
    t_g_mlm_text.w2s_msg_hdmi_0,
    t_g_mlm_text.w2s_msg_hdmi_1,
    t_g_mlm_text.w2s_msg_hdmi_2,
    t_g_mlm_text.w2s_msg_hdmi_3,
    t_g_mlm_text.w2s_msg_dvi,
    t_g_mlm_text.w2s_msg_dvi_0,
    t_g_mlm_text.w2s_msg_dvi_1,
    t_g_mlm_text.w2s_msg_dvi_2,
    t_g_mlm_text.w2s_msg_dvi_3,
    t_g_mlm_text.w2s_msg_vga,
    t_g_mlm_text.w2s_msg_vga_0,
    t_g_mlm_text.w2s_msg_vga_1,
    t_g_mlm_text.w2s_msg_vga_2,
    t_g_mlm_text.w2s_msg_vga_3,
    t_g_mlm_text.w2s_msg_dvd_0,
    t_g_mlm_text.w2s_msg_audio_0,
    t_g_mlm_text.w2s_msg_mmp,
    t_g_mlm_text.w2s_msg_mmp_0,
    t_g_mlm_text.w2s_msg_mmp_1,
    t_g_mlm_text.w2s_msg_mmp_2,
    t_g_mlm_text.w2s_msg_unknown
};

static UINT8* apui1_g_data_tbl[1] =
{
    at_g_compressed_eng
};

static SIZE_T az_g_data_len_tbl[1] =
{
    sizeof(at_g_compressed_eng)
};

static HANDLE_T h_g_lock = NULL_HANDLE;

/*-----------------------------------------------------------------------------
                    function declarations                                          
-----------------------------------------------------------------------------*/
static VOID _mlm_isl_decompress(UINT16 ui2_lang)
{
    INT32       i4_ret;
    HANDLE_T    h_zip_eng = NULL_HANDLE;
    SIZE_T      z_dest_len = sizeof(MLM_ISL_TEXT_T);

    if(ui2_lang >= 1)    /* MLM_ISL_LANG_NUM = 1 */
    {
        return;
    }

    do
    {
        i4_ret = c_cl_open_eng(SN_CL_ZIP, NULL, NULL, &h_zip_eng);
        if(i4_ret < 0)
        {
            break;
        }

        i4_ret = c_cl_decompress(h_zip_eng,
                                 apui1_g_data_tbl[ui2_lang],
                                 az_g_data_len_tbl[ui2_lang],
                                 0,
                                 CL_NULL_PARAM_TYPE,
                                 NULL,
                                 &t_g_mlm_text,
                                 &z_dest_len,
                                 NULL);
        if(i4_ret < 0)
        {
            break;
        }

    }while(0);

    if(i4_ret < 0)
    {
        c_memset(&t_g_mlm_text, 0, sizeof(MLM_ISL_TEXT_T));
    }

    if(h_zip_eng != (HANDLE_T)NULL)
    {
        c_cl_close(h_zip_eng);
    }
}

static VOID _mlm_isl_lock(VOID)
{

    /* Acquire lock */
    if(h_g_lock == NULL_HANDLE)
    {
        a_amb_lock();
        if(h_g_lock == NULL_HANDLE)
        {
            c_sema_create(&h_g_lock,
                          X_SEMA_TYPE_MUTEX,
                          X_SEMA_STATE_UNLOCK);
        }
        a_amb_unlock();
    }

    /* Lock */
    if(h_g_lock)
    {
        c_sema_lock(h_g_lock, X_SEMA_OPTION_WAIT);
    }
}

static VOID _mlm_isl_unlock(VOID)
{
    /* Unlock */
    if(h_g_lock)
    {
        c_sema_unlock(h_g_lock);
    }
}

UTF16_T* mlm_isl_get_text(UINT16 ui2_lang, UINT16 ui2_key)
{
    if(ui2_lang != ui1_g_mlm_cur_lang_idx)
    {
        _mlm_isl_lock();
        if(ui2_lang != ui1_g_mlm_cur_lang_idx)
        {
            _mlm_isl_decompress(ui2_lang);
            ui1_g_mlm_cur_lang_idx = ui2_lang;
        }
        _mlm_isl_unlock();
    }

#ifdef APP_MLM_CENTER_SUPPORT /* ExcelGen mechanism. */ 
    if (   (aw2s_g_txt_tbl[ui2_key][0] != 0 && aw2s_g_txt_tbl[ui2_key][0] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][1] != 0 && aw2s_g_txt_tbl[ui2_key][1] == (UTF16_T)L'^')  &&
           (aw2s_g_txt_tbl[ui2_key][2] != 0 && aw2s_g_txt_tbl[ui2_key][2] == (UTF16_T)L'I')  &&
           (aw2s_g_txt_tbl[ui2_key][3] != 0 && aw2s_g_txt_tbl[ui2_key][3] == (UTF16_T)L'D') )
    {
        extern UTF16_T* mlm_center_get_text_by_hint (CHAR* ps_module_name, UINT16 ui2_lang, UTF16_T* pw2s_hint);

        return mlm_center_get_text_by_hint ("ISL", ui2_lang, aw2s_g_txt_tbl[ui2_key]);
    }
#endif

    return aw2s_g_txt_tbl[ui2_key];
}

UINT16 mlm_isl_s639_to_langidx(ISO_639_LANG_T s639_lang)
{
    UINT16 ui2_lang_idx = 0; 

    if(s639_lang == NULL)
    {
        ui2_lang_idx = 0;
        return ui2_lang_idx;
    }
    if(c_strncmp(s639_lang,"eng",3) ==0)
    {
        ui2_lang_idx = 0; /*MLM_ISL_LANG_ENG*/
    }

#ifdef MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN
    return MLMGEN_CUSTOM_S639_TO_LANGIDX_REASSIGN("ISL", s639_lang, ui2_lang_idx);
#else
    return ui2_lang_idx;
#endif
}
VOID mlm_isl_langidx_to_s639(UINT16 ui2_lang,ISO_639_LANG_T s639_lang)
{
    if(s639_lang == NULL)
    {
        return;
    }
    switch(ui2_lang)
    {
        case 0: /*MLM_ISL_LANG_ENG*/
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
        default:
            c_strncpy(s639_lang,"eng",3);
            s639_lang[3] ='\0';
            break;
    }
}
